### ISSUE TITLE
when the cell width greater than the column width

### ISSUE THREAD

**Issue by spd-heshuip** [evrencoskun/TableView#10]
when the tableview load the data first time,if the cell width greater than the column width,the tableview show like that :
<img width="330" alt="2017-12-27 3 13 13" src="https://user-images.githubusercontent.com/8907462/34373890-d90b1d70-eb18-11e7-96fd-775601d08f91.png">
when I call the code:
<img width="702" alt="2017-12-27 3 20 48" src="https://user-images.githubusercontent.com/8907462/34374012-8d516410-eb19-11e7-8780-7c198ce991ed.png">

the tableview will show correct:
<img width="330" alt="2017-12-27 3 18 25" src="https://user-images.githubusercontent.com/8907462/34373934-38503b3a-eb19-11e7-8c7e-aeae6eeb990e.png">

**Comment by evrencoskun** [comment]
Do you have the below lines on your TableViewAdapter ? If you don't have. Please check the sample [TableViewAdapter](https://github.com/evrencoskun/TableView/blob/master/app/src/main/java/com/evrencoskun/tableviewsample/tableview/TableViewAdapter.java)

   ```
        // It is necessary to remeasure itself.
        viewHolder.cell_container.getLayoutParams().width = LinearLayout.LayoutParams.WRAP_CONTENT;
        viewHolder.cell_textview.requestLayout();
  ```
It shouldn't be necessary to call `notifyDataSetChanged`

**Comment by spd-heshuip** [comment]
Yeah,I check the code,it include that lines;
the version is 0.8.3;

**Comment by spd-heshuip** [comment]
I check the source code,In the ColumnLayoutManager.java,method measureChild(),when the column width not equal to cell width at the first time,it did not call the line:
<img width="712" alt="fb1f0eca-552e-4d94-9d0f-0cf08b75a18e" src="https://user-images.githubusercontent.com/8907462/34374740-9448a270-eb1d-11e7-8ea7-7b8e5c9cf482.png">

**Comment by evrencoskun** [comment]
m_nLastDx value will be '0' for first population process.  So 

if `shouldFitColumns` control returns true, then the below line will be called. 

`m_iCellLayoutManager.fitWidthSize(nPosition, false);
`

> when the column width not equal to cell width at the first time,it did not call the line:

You can check shouldFitColumns control. If it is necessary to fit column width values, it calls at end of visible row index. 



Anyway, Can you try the below codes instead using `Observable.timer` 

`tableView.getCellLayoutManager.fitWidthSize(false);`

After that if you still got the same problem.  Please try that;

```
// Force remeasure each cell header views
tableView.getColumnHeaderLayoutManager.customRequestLayout();
// Recalculate all of column width values.
`tableView.getCellLayoutManager.fitWidthSize(false);`
```

I will check your case on my leisure time. 

See you

**Comment by spd-heshuip** [comment]
Hi,Thank you for your reply!
I use the below codes instead using Observer.timer
<img width="505" alt="2017-12-28 9 11 57" src="https://user-images.githubusercontent.com/8907462/34397243-52548fcc-ebaf-11e7-95e7-8b61096328a5.png">
and the tableview will show normal,but it will shake like that: 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8907462/34397448-23bb7d0e-ebb1-11e7-8ba2-6229427fbeed.gif)

**Comment by evrencoskun** [comment]
Hi, 
It's shaking that's because of your `post runnable`
Because, It goes into the main thread queue and gets executed after the other pending tasks are finished. 

Let's try the below codes without using any thread process. 

```
// Force remeasure each cell header views
tableView.getColumnHeaderLayoutManager.customRequestLayout();
// Recalculate all of column width values.
`tableView.getCellLayoutManager.fitWidthSize(false);
```

And let me know the result.

**Comment by spd-heshuip** [comment]
I have try he below codes without using any thread process:
<img width="628" alt="2017-12-28 2 43 01" src="https://user-images.githubusercontent.com/8907462/34402576-6ed01ff8-ebdd-11e7-80ce-3d602f370c52.png">
but it will cause NullPointerException:
<img width="970" alt="2017-12-28 2 45 12" src="https://user-images.githubusercontent.com/8907462/34402624-c55ddd6a-ebdd-11e7-82c5-23f033ce82ce.png">

**Comment by spd-heshuip** [comment]
I upload the project to the dropbox,you can download the project and check that,Thanks!!
[https://www.dropbox.com/s/zrjtgcxsdoytnwn/TableView-master.zip?dl=0](url)
and I think I found the reason why the tableview show abnormality at the first time,because it did not got focus in the beginning;

**Comment by spd-heshuip** [comment]
Hi,did you try the sample code?

**Comment by evrencoskun** [comment]
Hello, 

Unfortunately, I haven't tried your code yet because of the celebration of new year.   In my first leisure time, I'll check it on.

Have a nice day.

**Comment by spd-heshuip** [comment]
OK,Thank you very much and wish you Happy new year!!

**Comment by evrencoskun** [comment]
Happy new year to you, too! :)

**Comment by evrencoskun** [comment]
Hi, 
The link seems broken. Could you fix it ? 

Thanks.

**Comment by spd-heshuip** [comment]
please try this:
https://www.dropbox.com/s/zrjtgcxsdoytnwn/TableView-master.zip?dl=0

**Comment by evrencoskun** [comment]
I have tested your codes. 

My first observation on your code, when I change 

```java
m_iTableView.postDelayed(new Runnable() {
            @Override
            public void run() {
                mStatusLayout.showContent();
            }
        }, 3000);
```
with 

```java
mStatusLayout.showContent();
```
It works perfectly. 

However, let's assume you need to above lines and don't want to change it. At that time, I realised that you modified the TableView codes. 

When I use the 0.8.5.1 version instead of yours, It works perfectly, even though using the above lines. 

If you don't want to horizontal lines of the TableView

you can use `app:show_horizontal_separator="false"` like this: 

 <com.evrencoskun.tableview.TableView
        android:id="@+id/tableView"
        android:layout_width="match_parent"
        app:show_horizontal_separator="false"
   ....
  >


 After that, you can insert a line view both your column header layout and corner layout  like I do on the sample app.


Well, why does your modified TableView  have got this bug ? 

Because, on CellLayoutManager 

        ```java
    // This below lines is for populating for the first time like fetching all data to display.
            // It shouldn't be worked when it is scrolling horizontally ."getLastDx() == 0"
            // control for it.
        } else if (m_iCellRecyclerView.getScrollState() == RecyclerView.SCROLL_STATE_IDLE &&
                childLayoutManager.getLastDx() == 0) {

            if (childLayoutManager.isNeedFit()) {
                m_bNeedFit = true;

                // all columns have been fitted.
                childLayoutManager.clearNeedFit();
            }

            if (m_bNeedFit) {
                // for the first time to populate adapter
                if (m_jRowHeaderLayoutManager.findLastVisibleItemPosition() == nPosition) {

                    // The below line helps to change left & right value of the each column
                    // header views
                    // without using requestLayout().
                    m_iColumnHeaderLayoutManager.customRequestLayout();

                    fitWidthSize(false);
                    Log.e(LOG_TAG, nPosition + " fitWidthSize populating data for the first time");

                    m_bNeedFit = false;
                }
            }
        }
```

Something you did causes on this control, `m_jRowHeaderLayoutManager.findLastVisibleItemPosition()` returns **-1** . 


I strongly recommend to you use the latest version without doing any modify.
