### ISSUE TITLE
Zebra view

### ISSUE THREAD

**Issue by joegillian** [evrencoskun/TableView#106]
Hi,

Thanks for this great library.

Is it possible you to add zebra view feature, so that odd/even rows or columns have different background colors?

I managed to do it by checking cells' positions and setting their background colors. At first it seemed ok but if I sort the rows  everything becomes messed up because row's background does not get updated by their new order. 
Thanks again.

**Comment by joegillian** [comment]
hi again,

i did it as you mentioned on issue  #69 but still same. Could it be that i set the background on wrong place? i do it in the onBindCellViewHolder.


![zebra](https://user-images.githubusercontent.com/37173926/39921318-19aa6ede-5523-11e8-9673-c3d771ab3173.gif)

**Comment by evrencoskun** [comment]
Hi @joegillian,

You need to update each of the background value of cell item. 

Assume that you have an tableView like this.
---------------
1.cellA : blue
2.cellB : white
3.cellC : blue
---------------

after sorting process, each cell item shows its own background color.
-----------------
1.cellC: blue
2.cellA: blue
3.cellB: white
------------------

So, what is the solution? You just need to update each of cell item after the sorting process.

just update your cell model data with right color and run the notifyDataSetChanged function of the TableViewAdapter

**Comment by joegillian** [comment]
Thanks, I did it as you say and I works perfect.

**Comment by evrencoskun** [comment]
Great! 

I think, the easiest way setting background color at binding process.

```java
@Override
     public void onBindCellViewHolder(AbstractViewHolder holder, Object cellItemModel, int 
             columnPosition, int rowPosition) {
          Cell cell = (Cell) cellItemModel;
          
          // Determine the right color considering to the row position;
          int bgColor = rowPosition % 2 == 0 ? myFirstColor : mySecondColor;
          
          // Set the background color to model
           cell.setBackgroundColor(bgColor);

           // Get the holder to update cell item value
           MyCellViewHolder viewHolder = (MyCellViewHolder) holder;
           viewHolder.setCell(cell);      
}
```

With this way, It will set the right color every time, not just for once. However, after sorting process, you need to call notifyDataSetChanged as well. Because, the cell items whose positions are unchanged after the sorting process, won't be notified.

**Comment by Aleksa-Smolovic** [comment]
I tried both this solution and the one at 69, it didn't work, also I have to change bg color of cell like this
app:unselected_color="@color/grayBlack", it doesn't work when I change it in cell layout. What to do?
