### ISSUE TITLE
Spacing between header and cell in Table view. The TableView does not display from start of activity

### ISSUE THREAD

**Issue by namtran4194** [evrencoskun/TableView#113]
Hi,
I'm using custom TableView. I'm facing the issue that there is a space between column header and cell view. and the TableView does not display from start of activity. I set TableView's width to "match_parent" and activity's width to "match_parent" too.
Please help me to fix this. Thanks!
![inkedscreenshot_20180514-172045_li](https://user-images.githubusercontent.com/13742650/39996619-565a7e26-57aa-11e8-8879-b20e4b76f66e.jpg)

**Comment by evrencoskun** [comment]
Hi @namtran4194 Which version do you use?

**Comment by namtran4194** [comment]
i use version 0.8.8 and the layouts and holders are based on your sample app

**Comment by evrencoskun** [comment]
Could you please share some code?

**Comment by namtran4194** [comment]
okie, i will share it tomorrow

**Comment by namtran4194** [comment]
Hi, here some code, please take a look.
https://github.com/namtran4194/smd

**Comment by evrencoskun** [comment]
I guess you tried to hide row header. But unfortunately, you can not hide the row headers. Because it helps to the TableView in some calculations.

```java
    @Override
    public AbstractViewHolder onCreateRowHeaderViewHolder(ViewGroup parent, int viewType) {
        return null;
    }

    @Override
    public void onBindRowHeaderViewHolder(AbstractViewHolder holder, Object rowHeaderItemModel, int rowPosition) {

    }

    @Override
    public View onCreateCornerView() {
        return null;
    }
```

**Comment by namtran4194** [comment]
Yeah, i want to hide row header because i don't need it. So how can i fix this?

**Comment by namtran4194** [comment]
After i add row header, corner view and fixed width - height for row header. All issues are gone.
Hope you work around to make TableView actually fit 'match_parent'

**Comment by ameybhandarkar** [comment]
> After i add row header, corner view and fixed width - height for row header. All issues are gone.
> Hope you work around to make TableView actually fit 'match_parent'

Could you please share that clculation code?

**Comment by ameybhandarkar** [comment]
Adding below lines in dimens.xml solved the issue

`<dimen name="default_row_header_width">55dp</dimen>
    <dimen name="default_column_header_height">40dp</dimen>`
