### ISSUE TITLE
Programatically set separator color

### ISSUE THREAD

**Issue by cstarner** [evrencoskun/TableView#115]
It would be nice to have the ability to set the separator color of the TableView programatically, like you can with shadow, selected and unselected. 

It doesn't look like a terrifically difficult change to make, and I'd be happy to submit a pull request to accomplish it. Is there any particular reason that this has not been included, or is it simply because no one has really needed it until now?

**Comment by sonique6784** [comment]
Hi @cstarner,
you can either use `app:separator_color="@color/your_color"`
or for more control extend the TableView and override : `protected DividerItemDecoration createItemDecoration(int orientation)`

But feel free to contribute and submit a pull request, I'm sure other people will enjoy this feature.

**Comment by cstarner** [comment]
For my use case, I can't declare TableView in XML; I'm using it to format data, and there is a bit of a delay until that data arrives. 

For the time being, I am subclassing it, but it's such an easy fix to make, I'd figured I'd test the waters to see if anyone else is interested

**Comment by naushad-madakiya** [comment]
is this available in latest 0.8.8 release? as I am not able to setSeparatorColor from table view

**Comment by evrencoskun** [comment]
0.8.8 doesn't support this feature. That's why you are not able to.  :/

**Comment by naushad-madakiya** [comment]
in which version I will be able to use this? 

I cloned the repo and while testing it seems `setSeparatorColor` is not working. As decorations are created already when we call `setSeparatorColor`

**Comment by evrencoskun** [comment]
I think It helps to set separator color when The TableView is at initializing process instead of run-time.  That means; with this function, you can not change separator color after the TableView is visible on the screen. 

As you can see the source codes of the TableView. It creates DividerItemDecoration for each recyclerViews just one time. So if you want to set separator color dynamically, you need to modify the codes or find another way to set your custome DividerItemDecoration for each RecyclerView. 

```java
@Override
    public DividerItemDecoration getVerticalItemDecoration() {
        if (mVerticalItemDecoration == null) {
            mVerticalItemDecoration = createItemDecoration(DividerItemDecoration.VERTICAL);
        }
        return mVerticalItemDecoration;
    }

    protected DividerItemDecoration createItemDecoration(int orientation) {
        Drawable divider = ContextCompat.getDrawable(getContext(), R.drawable.cell_line_divider);

        // That means; There is a custom separator color from user.
        if (mSeparatorColor != -1) {
            // Change its color
            divider.setColorFilter(mSeparatorColor, PorterDuff.Mode.SRC_ATOP);
        }

        DividerItemDecoration itemDecoration = new DividerItemDecoration(getContext(), orientation);
        itemDecoration.setDrawable(divider);
        return itemDecoration;
    }
```

**Comment by naushad-madakiya** [comment]
yup, I went through the same source code, I will try to override the `createItemDecoration` by extending `TableView` and pass the separator color I want.

**Comment by nikitoSha** [comment]
@evrencoskun  Hi! How to change width of separator? I need bold lines between cells :(
