### ISSUE TITLE
How to change the height of corner view?

### ISSUE THREAD

**Issue by JairoBarzola** [evrencoskun/TableView#119]
I have this problem , in my xml of corner view  I put  android:layout_height="40dp" and in xml of column header the same height. 
<img width="285" alt="captura de pantalla 2018-05-20 a la s 20 08 53" src="https://user-images.githubusercontent.com/22141461/40286138-26709730-5c6a-11e8-9319-c190672262a5.png">

**Comment by evrencoskun** [comment]
Hi @JairoBarzola ,

According to your picture, they have same height as well. 
![fef6bb12-a346-4eb2-83ec-d3def3604d4e](https://user-images.githubusercontent.com/4228262/40582538-3d9338ce-6182-11e8-806e-6c4b4857c8d3.jpg)

It seems you didn't use the `column_header_height` like [this](https://github.com/evrencoskun/TableView#xml).  So, your tableView uses the default height values. 

You can override the height value adding same dimen tags on your project. 

    ```
    <!-- Overriding the default values of the tableView -->
    <dimen name="default_row_header_width">35dp</dimen>
    <dimen name="default_column_header_height">20dp</dimen>
```
