### ISSUE TITLE
Row headers scroll independently sometimes

### ISSUE THREAD

**Issue by SparkleBirdie** [evrencoskun/TableView#122]
Cells fling horizontally first, then scroll row header at the same time, and they move each other,  row headers scroll independantly and the cells stand still.
Move cells up and move row header down, the two parts move independently.
![device-2018-05-27-231805](https://user-images.githubusercontent.com/2926632/40587644-b2accd78-6204-11e8-8d2e-8b05f0e06db5.png)

**Comment by evrencoskun** [comment]
Hi @SparkleBirdie , 

Yeah. this is a known bug.  There was the same situation for ColumnHeader and Cell too. But It has been fixed with 0.8.8 version.

**Comment by SparkleBirdie** [comment]
@evrencoskun Thanks for your reply, my project is on v0.8.8, it occurs too.

**Comment by Clinan** [comment]
I also had this bug,0.8.8 and 0.8.7 all solute it.

**Comment by AvaneeshAsokan** [comment]
@evrencoskun First of all thanks for putting out this project. I, like the others, have been facing the same issue. In my case, which scrolling the rows of the row headers that comes into view seen to have large view heights.

![screenshot_20180614-172040](https://user-images.githubusercontent.com/40267129/41410575-853e6a8a-6ff7-11e8-94e8-bfd3fad2541e.png)
![screenshot_20180614-172045](https://user-images.githubusercontent.com/40267129/41410576-8576e900-6ff7-11e8-9ee3-0d11397b27c4.png)
![screenshot_20180614-172051](https://user-images.githubusercontent.com/40267129/41410577-85ae4d0a-6ff7-11e8-8c93-fff5e6559633.png)
![screenshot_20180614-172057](https://user-images.githubusercontent.com/40267129/41410578-85e0e558-6ff7-11e8-9e6a-c28f3c0492e3.png)
