### ISSUE TITLE
 How to replace the'corner'in the upper left corner

### ISSUE THREAD

**Issue by wangyangke** [evrencoskun/TableView#124]
hi, How to replace the'corner'in the upper left corner，I need to change corner to what I need, such as column names.Thanks for your help

**Comment by wangyangke** [comment]
can you help me

**Comment by evrencoskun** [comment]
Hi @wangyangke 

If you want to change your corner view, you can use different xml layout in your TableViewAdapter.

```java
@Override
     public View onCreateCornerView() {
         // Get Corner xml layout
         return LayoutInflater.from(context).inflate(R.layout.my_table_view_corner_layout, null);
}
```

**Comment by wangyangke** [comment]
@evrencoskun I'm sorry.Maybe my problem description is wrong, so you didn't understand me ,i need change The upper left corner of the "corner",After setting the rows and columns, the "Corner"  in the top left corner is still displayed in the tableview, and I need to change the "Corner" in the top left corner to my label,and I'm going to label it to explain the row in the first column

**Comment by wangyangke** [comment]
Thank you very much for your help. Good luck to you
