### ISSUE TITLE
Disorderly effect

### ISSUE THREAD

**Issue by wangyangke** [evrencoskun/TableView#125]
When the page opens, you can see OK, but if the page has other elements, tableView does not display the state. When I slide to tableView, the rowHeader information will be disorderly. When I roll back from right to left again, the interface is restored to the effect I want, and what's strange about this, I think of tableView as a reason. A sub element is placed in the RecyclerView

**Comment by evrencoskun** [comment]
Hi @wangyangke, 

> When the page opens, you can see OK, but if the page has other elements, tableView does not display the state. 

In order to be clearer,  please share a gif that displays your case. Because I  don't get what you mean exactly.
