### ISSUE TITLE
how to get cell value (1,rowclicked) when use rowheaderclick after sort descending

### ISSUE THREAD

**Issue by tongtt5611** [evrencoskun/TableView#126]
```java
@Override
    public void onRowHeaderClicked(@NonNull RecyclerView.ViewHolder p_jRowHeaderView, int
            p_nYPosition) {
        CellModel cellModel = (CellModel) mTableView.getAdapter().getCellItem(1, p_nYPosition);
        System.out.println("cellModel id=" + cellModel.getId());
        System.out.println("cellModel content=" + cellModel.getContent().toString());
    }
```
After sort descending,  i can't get right value.
First data is:
    id       time       
1   1        20
2   2        15
3   3        30
After sort descending cloumun "id", data is:
     id       time
1   3        30
2   2        15
3   1        20
First when i click rowheader 1 --> value cellModel content time = 20
But after sort i click rowheader 1 --> value cellModel content time is still 20 but i want value is 30.
Can you help me?
Thanks.

**Comment by evrencoskun** [comment]
after sorting process, you need to call `notifyCellDataSetChanged`

```java
// mTableView.sortColumn...
mTableView.getAdapter().getCellRecyclerViewAdapter().notifyCellDataSetChanged();
```

**Comment by tongtt5611** [comment]
thanks you.
i update to version 0.8.8.
i can use mTableView.getAdapter().getCellRowItems(p_nYPosition);
thanks for your attention
