### ISSUE TITLE
Is there a way to disable the selection?

### ISSUE THREAD

**Issue by tuvirus** [evrencoskun/TableView#143]
Hello, @evrencoskun 

Currently i'm having issues with the selectiongHandler. First, ok it does unselect the item but when i scroll, i'm using tabs by the way, to another tab and return the selection still there. I think it is a bu, also if if i have many columns when i unselect and scroll horiontally on the table it shows me the selection again, so might be a bug. So i went to anther solution, disable the selection is there a way to disable? set the selection to false or should i null the selection handler?

**Comment by evrencoskun** [comment]
Hi @tuvirus, 

Probably, 0.8.8 version has got a selection bug as you mention. 

To ignore setting selection colors that are displayed by user interaction, the below line can be used.
   
` tableView.setIgnoreSelectionColors(false);`

**Comment by tuvirus** [comment]
Where should I use it? I'm using it in my activity class. But doesn't work. I was planning just comment the selection states so it doesn't change the color.

**Comment by evrencoskun** [comment]
when you initialize your tableView, you should use it.
