### ISSUE TITLE
App crashes on Vertical stroll with editTexts

### ISSUE THREAD

**Issue by nelson-bighetti** [evrencoskun/TableView#154]
I am using editTexts instead of textviews and I'm requesting focus for the editText when a cell is clicked.
However, when I scroll vertically, the app crashes when the focused editText reaches the top or the bottom of the screen. 
I noticed that this doesn,t happen when I scroll horizontally and that it's probably because the focused editText loses focus on horizontal scroll.
How to fix this issue?
![ezgif com-gif-maker 1](https://user-images.githubusercontent.com/20903830/44573271-dbd27e80-a78e-11e8-927f-07366501f5e4.gif)

**Comment by nelson-bighetti** [comment]
@evrencoskun 
![screenshot from 2018-09-16 13-29-42](https://user-images.githubusercontent.com/20903830/45595475-0fcb4900-b9b5-11e8-85ef-62436723ce73.png)
The method I am trying to call is changeCellItem

**Comment by evrencoskun** [comment]
@nelson-bighetti 

I think you should google considering the exception error. Because it is not related specifically with TableView. 

check [this ](https://stackoverflow.com/questions/27070220/android-recyclerview-notifydatasetchanged-illegalstateexception)

**Comment by nelson-bighetti** [comment]
@evrencoskun Fixed it. Thank you so much!
