### ISSUE TITLE
Unable to set _appbar_scrolling_view_behavior_

### ISSUE THREAD

**Issue by sagarpatel288** [evrencoskun/TableView#162]
When using as below:
```
<coordinatorLayout - 
          <appbarLayout - 
                <collapsing toolbar layout
             ---
          </appbarLayout>

         <LinearLayout
                     id= fragmentContainer
                     app:layout_behavior="@string/appbar_scrolling_view_behavior"
         </LinearLayout>
</coordinatorLayout>
```

The *TableView* is inside fragment and it is not transferring the fling or scrolling to appbar layout...

**Comment by sagarpatel288** [comment]
Thanks for the quick reply. It is working as per your suggestion there. However, is there a way I can scroll header too off the screen?
By the way, thanks for **The amazing TableView**

**Comment by evrencoskun** [comment]
Thanks @sagarpatel288 

> is there a way I can scroll header too off the screen?
I don't get what you mean

**Comment by sagarpatel288** [comment]
It is behaving like how toolbar behaves with collapseMode="pin"... so, the header (columns having titles like large column and so...) gets clipped when reaching at top of the screen and all cell items are scrolling underneath the header...

**Comment by evrencoskun** [comment]
There is no any implementation to make it like you want. But you can try to find out the way using "`ColumnHeaderRecyclerView` that is the view that is represented as a Column Header.
