### ISSUE TITLE
Auto sizing to full size and setting columns widths manual

### ISSUE THREAD

**Issue by nielsnl68** [evrencoskun/TableView#18]
Hello, 
Thanks for this view. I'm trying to set the column widths so the tableview matching the parent width.

I tried to set the columnheader widths in your example but they are overruled by the cell widths atm.  removing the row to set the width at the cell did not work as well.

I think the width of the column header should be the main value. Only when it is set to WRAP_CONTENT it should use the max width of the cells.

What i also love to see is an option that allows the following; By default when the viewtable's layout_width is set to match_parent the last column would be sized to fill the space to the right.  
To allow stretching an other column we should introduce a new property named something like "StretchColumn". 

Is this easy to implement? I Love to help by i haven't got around yet how everything is working yet.

**Comment by evrencoskun** [comment]
Hi @nielsnl68,

You can achieve your want without waiting new version of TableView. 

> I tried to set the columnheader widths in your example but they are overruled by the cell widths atm. removing the row to set the width at the cell did not work as well.

As far as I understand first request is you don't want to recalculation column width of TableView.

If your column width values are constant, then first thing you should do use the below code. 

`tableView.setHasFixedWidth(false);`

After that, you shouldn't write like this on `onBindCellViewHolder` and `onBindColumnHeaderViewHolder`  in your TableViewAdapter.

```java
 // It is necessary to remeasure itself.
        viewHolder.cell_container.getLayoutParams().width = LinearLayout.LayoutParams.WRAP_CONTENT;
        viewHolder.cell_textview.requestLayout();
```
And of course, your tableView_layout should contains constant width values.

```java
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    android:id="@+id/cell_container"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="your_size_dp"
    android:layout_height="@dimen/cell_height"
    android:background="@color/cell_background_color"
    android:orientation="vertical">


    <TextView
        android:id="@+id/cell_data"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center_vertical"
        android:layout_marginStart="10dp"
        android:layout_marginEnd="10dp"
        android:gravity="center"
        android:maxLines="1"
        android:textColor="@color/table_view_default_text_color"
        android:textSize="@dimen/text_size"
        tools:text="Cell Data"/>

</LinearLayout>
```

However, assume that your columns width constant but different from each other like below.


       100dp   |           200  dp        |    40dp    |
------------|-------------------|-----------|-------

At that time, you can set width value according to column position in onBind functions like this.


```java
  @Override
    public void onBindCellViewHolder(AbstractViewHolder holder, Object p_jValue, int
            p_nXPosition, int p_nYPosition) {
        Cell cell = (Cell) p_jValue;

        // Get the holder to update cell item text
        CellViewHolder viewHolder = (CellViewHolder) holder;
        viewHolder.cell_textview.setText(String.valueOf(cell.getData()));
      
      int columnWidth = (int) (100 * context.getResources().getDisplayMetrics().density);
      switch(p_nXPosition){
             case 1: 
                columnWidth = (int) (200 * context.getResources().getDisplayMetrics().density);
              break;
             case 2: 
                  columnWidth = (int) (40 * context.getResources().getDisplayMetrics().density);
              break;
       }
        viewHolder.cell_container.getLayoutParams().width = columnWidth
        viewHolder.cell_textview.requestLayout();
    }
```

You should also do same setting on `onBindColumnHeaderViewHolder` 


Besides, there is another way I can show you for that, 
You can also set width value of columns considering to `getCellItemViewType ` and `getColumnHeaderItemViewType`

For this TableView 

      100dp   |           200  dp        |    40dp    |
------------|-------------------|-----------|-------

You can create 3 types of item for both cell and column

 ```java
@Override
    public int getColumnHeaderItemViewType(int position) {
        // For this example, we have 3 view type for column header
        // there are it returns for 0. position -> 0 , 1. position -> 1  and 2. position -> 2
        return position;
    }


    @Override
    public int getCellItemViewType(int position) {
        // For this example, we have 3 view type for cell items like column headers
        // there are it returns for 0. position -> 0 , 1. position -> 1  and 2. position -> 2
        return position;
    }
```

After that, on your TableViewAdapter you can use 3 type of different layout without setting width value dynamically.

Let we create 3 different Cell item layout like this;

- **type_0_cell_item_layout.xml** (it has 100dp width value)
- **type_1_cell_item_layout.xml** (it has 200dp width value)
- **type_2_cell_item_layout.xml**   (it has 40dp width value)

And 

```
 @Override
    public RecyclerView.ViewHolder onCreateCellViewHolder(ViewGroup parent, int viewType) {
       
       View layout = null 

       // Getting layout according to view type
        switch{
           case 0: 
                layout = LayoutInflater.from(m_jContext).inflate(R.layout.type_0_cell_item_layout,
                parent, false);
            break;
             case 1: 
                layout = LayoutInflater.from(m_jContext).inflate(R.layout.type_1_cell_item_layout,
                parent, false);
            break;
            case 2: 
                layout = LayoutInflater.from(m_jContext).inflate(R.layout.type_2_cell_item_layout,
                parent, false);
            break;
        }

        // Create a Cell ViewHolder
        return new CellViewHolder(layout);
    }
```

You should do the same implementation on `onCreateColumnHeaderViewHolder` like below.

That are the difference between both of ways. 

- If you want to set width value dynamically, you should use first way. But every time the viewholder is binded, lines for setting width value will be called. 
- If you don't like the first approach, you use the second way. However, worst part of this approach, you need to create an xml layout for each columns which have different width values. 

Of course, It would be great to set max width value for columns without using both ways. Actually, I am planning to do that before release 1.0 version. 

For now you can make do with both of ways.


> What i also love to see is an option that allows the following; By default when the viewtable's layout_width is set to match_parent the last column would be sized to fill the space to the right.
> To allow stretching an other column we should introduce a new property named something like "StretchColumn".


Using above approaches, you can also achieve this. But,I know, it is not as much as flexible to do that.

 I have written down your both requests. In my opinion, 1.0 version should has these type of features.

Thanks for feedback,

**Comment by nielsnl68** [comment]
Thanks for your information. 

I will try to implement it. I do not want to set the width in the xml files as your last option. For now I added a width value in the columnheadermodel what i use to size the header widths in the onBindColumnHeaderViewHolder. Somehow i need to get that value from the columnheadermodel when i set the onBindCellViewHolder. I don't want to set it for every cellmodel.

btw in your example you use:  `
> (int) (pColumnHeaderModel.getWidth() * context.getResources().getDisplayMetrics().density);
The value context is not resolving. any suggestion on how to get it?

thanks again for your time.

`

**Comment by djinnovations** [comment]
hi,
I went through most your layout managers and listener especially, man i have to say, tears of joy, such deep understand of layout managers and recyclerview and this table view is really a bench mark. A bow my end. Thanks for this amazing project.

I have the same requirement like what your trying to say in the above discussion. Since this issue is marked closed, I will raise a new issue, if you don't mind. I will attach a video too for you too look at. Thanks for your time

**Comment by evrencoskun** [comment]
Hi @djinnovations 

Thanks for your kind words. I reopened the issue for you.
