### ISSUE TITLE
How to set individual cell width dynamically?

### ISSUE THREAD

**Issue by diptikas** [evrencoskun/TableView#189]
My requirement is to set cell width dynamically as per text length so I don't want to reset complete column width as per current implementation column will take width of longest cell .

I want to set individual cell width and scroll properly.

Please tell me how to achieve that?

**Comment by nikitoSha** [comment]
Just set чоПопалоКласс.СделатьЧоПопало(); and all be okay

**Comment by evrencoskun** [comment]
With 0.8.8 version, Column width values can be set programmatically using the below function.

`setColumnWidth(int columnPosition, int width)`

**Comment by u-barnwal** [comment]
Hi @evrencoskun, where should I call this `setColumnWidth()`?

I am doing it like this and it's not working

`tvProducts.post(() -> {`
`      binding.tvProducts.setColumnWidth(0, 1000);`
`});`

tvProducts being my TableView
