### ISSUE TITLE
Column and Cell width desynchronization

### ISSUE THREAD

**Issue by vkhaitan** [evrencoskun/TableView#191]
I am using this UI Element through Xamarin.Android . I ported it myself.

There is an issue which I am facing. setHasFixedSize() makes column and cell desynchronized. Columns has different width, cells have different width. So it becomes zigzag. In fact, all the cells in a column are of different width. I am also using RemeasureColumnWidth() .

This is the offending code - 
            this.HasFixedWidth = true; // Removing this line fixes the issue.
            for (int i = 0; i < columnData.Count; ++i)
            {
                RemeasureColumnWidth(i);
            }
Why would you allow cell to be desynchronized, it simply baffles me.

<img width="443" alt="save" src="https://user-images.githubusercontent.com/15922747/49002608-0fee7e80-f186-11e8-9907-ae0c1d0ac62c.png">

**Comment by vkhaitan** [comment]
I was trying to solve an issue that after changing the content of Table, I remeaserwidth and it works fine with content hugging width. However, Once I start scrolling, its width change after 1 row scroll. The new width is equal to the largest width table acquired in its existence(which means maximum width during data changes). Why so ?

**Comment by vkhaitan** [comment]
I tried everything I could, but this cell width resize is still happening. Because of RemeasureWidth(), cell is resizing to fit requirements. However, during scroll its size increases to equal historical maximum size. How does TableView remember what was historical maximum size of TableView Column ?

**Comment by evrencoskun** [comment]
Hi @vkhaitan,

Why do you need to use  `setHasFixedSize()` ?,  You shouldn't use the method which is for some performance control on RecyclerView.  However, in TableView the size is not fixed. so you shouldn't use that.  Please check [this](https://stackoverflow.com/a/33365341/3360584). 

In TableView, The proper width value for each column is stored in TableView to be ready for new calculation at vertical scrolling process. 

If you want to know, what's going on in the process, please check, [ColumnWidthHandler](https://github.com/evrencoskun/TableView/tree/master/tableview/src/main/java/com/evrencoskun/tableview/handler), [CellLayoutManager](https://github.com/evrencoskun/TableView/blob/master/tableview/src/main/java/com/evrencoskun/tableview/layoutmanager/CellLayoutManager.java)

**Comment by vkhaitan** [comment]
Okay, I found that my issue is fixed in issue [169](https://github.com/evrencoskun/TableView/pull/169) . So now scrolling is properly working without wrong width.
