### ISSUE TITLE
Scroll TableView programmatically by the desired column position 

### ISSUE THREAD

**Issue by evrencoskun** [evrencoskun/TableView#21]
> one question: for your TableView library, how do you scroll to a column say column 20?

Hi @sidharthshah,

It is actually pretty simple. If you checked the source code, you can see TableView occurs from 3 Skilled RecyclerViews. 

If you want to scroll horizontally, you can use `scrollToPosition` method of LayoutManager. 

For example: 

```java
        int position = 10;

        scrollCell(position);
        scrollColumnHeader(position);
```

Below helper methods will be on the new version too. For now, you can insert them on your project.

```java
private void scrollCell(int columnPosition) {
        CellLayoutManager cellLayoutManager = tableView.getCellLayoutManager();

        for (int i = cellLayoutManager.findFirstVisibleItemPosition(); i < cellLayoutManager
                .findLastVisibleItemPosition() + 1; i++) {

            ColumnLayoutManager columnLayoutManager = (ColumnLayoutManager) ((RecyclerView)
                    cellLayoutManager.findViewByPosition(i)).getLayoutManager();

            columnLayoutManager.scrollToPosition(columnPosition);
        }
    }

    private void scrollColumnHeader(int columnPosition) {
        tableView.getColumnHeaderLayoutManager().scrollToPosition(columnPosition);
    }
```

**Comment by gmcodebuster** [comment]
I have added above 2 methods in AbstractTableAdapter class of library and calling both method in Fragment onCreateView() after setting Adapter. In my case scrollColumnHeader(position) scrolls header to specific position, but scrollCell(position) does not scroll cell columns to specific position.

Can you tell me what I am doing wrong?

**Comment by evrencoskun** [comment]
Hi @gmcodebuster, 

The reason is TableView stores scroll position for Cell columns.

In CellRecyclerViewAdapter, TableView sets each cell column scroll position when before each cell row is getting visible. See below code  

```java
@Override
    public void onViewAttachedToWindow(RecyclerView.ViewHolder holder) {
        super.onViewAttachedToWindow(holder);

        // The below code helps to display a new attached recyclerView on exact scrolled position.
        CellRowViewHolder viewHolder = (CellRowViewHolder) holder;
        ((ColumnLayoutManager) viewHolder.m_jRecyclerView.getLayoutManager())
                .scrollToPositionWithOffset(m_iHorizontalListener.getScrollPosition(),
                        m_iHorizontalListener.getScrollPositionOffset());
```

So, below functions don't work before TableView cell is not visible on screen.

```java
scrollCell(position);
        scrollColumnHeader(position);
```


You can say "What is the solution on my case ?" 

You need to find a way to call above codes after when all cell is visible. or You need to hack TableView source to change default values of `HorizontalRecyclerViewListener` class. 

or last suggestion what the new version that will be release tomorrow. 


See you

**Comment by evrencoskun** [comment]
Hi @gmcodebuster @sidharthshah,

0.8.5.4 version has been just released. With this version there are 2 helper method in TableView.

These are ;

```java
tableView.scrollToColumnPosition(int column)
tableView.scrollToRowPosition(int row)
```

These methods will help your request. 

Please test your issue and let me know the result.

**Comment by gmcodebuster** [comment]
@evrencoskun ,

Thanks for adding scroll to position in recent release. I will integrate it in code and inform you about result.

**Comment by gmcodebuster** [comment]
@evrencoskun,
Scroll to position works perfectly.
