### ISSUE TITLE
When I slide the table to the back, when there is a data update, it will automatically roll to the first column. Can I just update the data without scrolling?

### ISSUE THREAD

**Issue by wangyangke** [evrencoskun/TableView#211]
When I slide the table to the back, when there is a data update, it will automatically roll to the first column. Can I just update the data without scrolling?

**Comment by evrencoskun** [comment]
Hi @wangyangke , 

If you want to change specific content on TableView without scrolling, for that, there are some helper methods on your TableViewAdapter.

Please check #59
