### ISSUE TITLE
Unfortunately,TableViewSample has stopped

### ISSUE THREAD

**Issue by yAnUARw** [evrencoskun/TableView#214]
I Can't  running this project smootly because I get error "Unfortunately,TableViewSample has stopped" when I am running it. Note: No Found error when rebuild this project

**Comment by MGaetan89** [comment]
@yAnUARw can you try with the latest `master`? I don't have any issue running the sample project (expect the one that will be fixed in #268).

**Comment by MGaetan89** [comment]
@yAnUARw  the fix was merged in `master`. Can you close this issue if it works for you?

**Comment by MGaetan89** [comment]
Hi @yAnUARw. Can you close this issue if v0.8.9 works as expected for you?
