### ISSUE TITLE
Null pointer while set items

### ISSUE THREAD

**Issue by LuciferLAPD** [evrencoskun/TableView#217]
class TableAdapter(context: Context, data: ArrayList<User>) :
		AbstractTableAdapter<ColumnHeaderModel, RowHeaderModel, CellModel>(context)
{
	override fun onCreateColumnHeaderViewHolder(parent: ViewGroup?, viewType: Int): AbstractViewHolder
	{
		val layout = LayoutInflater.from(mContext).inflate(R.layout.tableview_column_header_layout, parent, false)
		
		return ColumnHeaderViewHolder(layout, tableView)
	}
	
	init
	{
		setAllItems(createColumnHeaderModelList(), createRowHeaderList(data.size), createCellModelList(data))
	}
	
	private fun createColumnHeaderModelList(): List<ColumnHeaderModel>
	{
		val list = ArrayList<ColumnHeaderModel>()
		
		// Create Column Headers
		list.add(ColumnHeaderModel("Id"))
		list.add(ColumnHeaderModel("Name"))
		Log.d("zzz", "Column $list")
		return list
	}
	
	private fun createCellModelList(userList: List<User>): List<List<CellModel>>
	{
		val lists = ArrayList<List<CellModel>>()
		
		// Creating cell model list from User list for Cell Items
		// In this example, User list is populated from web service
		
		for (i in userList.indices)
		{
			val list = ArrayList<CellModel>()
			
			list.add(CellModel("1-$i", userList[i].id))          // "Id"
			list.add(CellModel("2-$i", userList[i].name))        // "Name"
			
			// Add
			lists.add(list)
		}
		
		Log.d("zzz", "Cell $lists")
		return lists
	}
	
	private fun createRowHeaderList(size: Int): List<RowHeaderModel>
	{
		val list = ArrayList<RowHeaderModel>()
		
		
		for (i in 0 until size)
		{
			// In this example, Row headers just shows the index of the TableView List.
			list.add(RowHeaderModel("${i + 1}"))
		}
		Log.d("zzz", "Row $list")
		return list
	}
	
	override fun onBindColumnHeaderViewHolder(holder: AbstractViewHolder?,
	                                          columnHeaderItemModel: Any?,
	                                          columnPosition: Int)
	{
		val columnHeader = columnHeaderItemModel as ColumnHeaderModel
		
		// Get the holder to update cell item text
		val columnHeaderViewHolder = holder as ColumnHeaderViewHolder
		
		columnHeaderViewHolder.setColumnHeaderModel(columnHeader, columnPosition)
	}
	
	override fun onBindRowHeaderViewHolder(holder: AbstractViewHolder?, rowHeaderItemModel: Any?, rowPosition: Int)
	{
		val rowHeaderModel = rowHeaderItemModel as RowHeaderModel
		
		val rowHeaderViewHolder = holder as RowHeaderViewHolder
		rowHeaderViewHolder.row_header_textview.text = rowHeaderModel.data
	}
	
	override fun onCreateRowHeaderViewHolder(parent: ViewGroup?, viewType: Int): AbstractViewHolder
	{
		val layout = LayoutInflater.from(mContext).inflate(R.layout.tableview_row_header_layout, parent, false)
		
		// Create a Row Header ViewHolder
		return RowHeaderViewHolder(layout)
	}
	
	override fun getCellItemViewType(position: Int): Int
	{
		return 0
	}
	
	@SuppressLint("InflateParams")
	override fun onCreateCornerView(): View
	{
		return LayoutInflater.from(mContext).inflate(R.layout.tableview_corner_layout, null, false)
	}
	
	override fun getColumnHeaderItemViewType(position: Int): Int
	{
		return 0
	}
	
	override fun getRowHeaderItemViewType(position: Int): Int
	{
		return 0
	}
	
	override fun onCreateCellViewHolder(parent: ViewGroup, viewType: Int): AbstractViewHolder
	{
		val layout: View = LayoutInflater.from(mContext).inflate(R.layout.tableview_cell_layout,
		                                                         parent, false)
		
		// Get default Cell xml Layout
		
		// Create a Cell ViewHolder
		return CellViewHolder(layout)
	}
	
	override fun onBindCellViewHolder(holder: AbstractViewHolder, p_jValue: Any, p_nXPosition: Int, p_nYPosition: Int)
	{
		val cell = p_jValue as CellModel
		
		(holder as CellViewHolder).setCellModel(cell, p_nXPosition)
	}
	
}

error at line setAllItems()

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.evrencoskun.tableview.adapter.recyclerview.ColumnHeaderRecyclerViewAdapter.setItems(java.util.List)' on a null object reference
        at com.evrencoskun.tableview.adapter.AbstractTableAdapter.setColumnHeaderItems(AbstractTableAdapter.java:86)
        at com.evrencoskun.tableview.adapter.AbstractTableAdapter.setAllItems(AbstractTableAdapter.java:117)
        at org.goat.utils.tableView.TableAdapter.<init>(TableAdapter.kt:27)

**Comment by MagoMtz** [comment]
i have the same issue. Did you solve it?

**Comment by LuciferLAPD** [comment]
set adapter for table view before set data for adapter. but this lib very
slow

Vào Th 5, 28 thg 3, 2019 vào lúc 01:37 MagoMtz <notifications@github.com>
đã viết:
