### ISSUE TITLE
Null data when filtering all table

### ISSUE THREAD

**Issue by MagoMtz** [evrencoskun/TableView#219]
Hi

Whe use the  

`tableViewFilter.set(filterKeyword);`

my data value from CellModel is null, causing a `NullPointerException` when trying to return for `getFilterableKeyword()`

`id` value from CellModel is 1-0

It does not happen when the column is set.

 Greetings 

![Captura](https://user-images.githubusercontent.com/11773351/55198153-7e663c00-517a-11e9-8665-92b01f30ff30.PNG)

### Edit: 

Solved. Just ad null checker in data and works perfect.

**Comment by MGaetan89** [comment]
@MagoMtz can you close this issue, as you found a solution to your problem?
