### ISSUE TITLE
TableView'i eklediğmde, Gradle, compile etmiyor

### ISSUE THREAD

**Issue by cansuvtek** [evrencoskun/TableView#22]
Merhabalar,

Github da bulunan projenizde kütüphaneyi bulamadım projemede ekleyemedim.

Tableview kontrolü projemdeki palette yok.Grid mantığıyla boğuşuyorum bulduğum en iyi proje, bir şekilde adım adım ilerlemek istiyorum.

İlk olarak bir kontrol atayım dedim sonrasında bir kütüphane ihtiyacım mı varki diye araştırmaya koyuldum.Bana yardımcı olabilirseniz sevinirim.

İyi çalışmalar

**Comment by cansuvtek** [comment]
dependencies {
 compile 'com.evrencoskun.library:tableview:0.8.5.1' 
}

>>>>>>build.grandle ekledikten sonra bu hatayı almaktayım.

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@label value=() from AndroidManifest.xml:12:9-25
	is also present at [com.evrencoskun.library:tableview:0.8.5.1] AndroidManifest.xml:13:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:9:5-46:19 to override.

>>>>>>AndroidManifest.xml de android:label="vTerminal" etiketini sildiğimde ise bu hatayı alıyorum.
>>>>>> tools:replace="android:label" etiketini eklediğimde de bu hatayı alıyorum.

Error:(15, 21) No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

**Comment by evrencoskun** [comment]
Selam Cansu, yaşadığın problem TableView'ile alakalı bir durum değil. 

Sana örnek olması açısından TableViewSample uygulamasının [build.gradle](https://github.com/evrencoskun/TableViewSampleApp/blob/master/app/build.gradle) dosyasına bakmanı öneriyorum.

**Comment by cansuvtek** [comment]
Bu sayfada gösterdiğiniz gibi aslında;

https://github.com/evrencoskun/TableView/commit/34260a2a8392b4979efab47388a4658567df3f49

 -- compileSdkVersion  25 -- olmasıyla alakalıymış benim sorunum.
-- compileSdkVersion  27  -- yaparak sorun çözüldü.

**Comment by evrencoskun** [comment]
Selam Cansu,

Probleminin sebebi, 

TableView içerisinde kullanılan aşağıdaki library'lerin senin uygulamanda derlenmemesi. 

```
compile 'com.android.support:appcompat-v7:27.0.2'
compile 'com.android.support:recyclerview-v7:27.0.2'
```

Senin `compileSdkVersionun ` **25** oldugundan hata alıyordu. 


**Çözümü: ** seninde paylaştığın gibi, `compileSdkVersionun  `versiyonunu güncellemek.


Yaşadığın problem çözüldüyse, #22 issue'yu kapatıyorum.

Bir sonra ki, olası problemin için, ayrı bir issue oluştursan sevinirim. 


Kolay gelsin.
