### ISSUE TITLE
maximum number of column?

### ISSUE THREAD

**Issue by cipcipp** [evrencoskun/TableView#225]
hello there..
i have table with size 20x5 (20 column, 5row). i've set it up correctly. At first when the size of table is 15x5 everything works fine, but when i extend to 20 columns and i scroll it horizontally, it crashed at end of the 15th column with error IndexOutOfBound; index 15 size 15. I also tried using 16 column, it crash with same error as well.

i hope in TableView Example there's shown >15 column but it shows exactly 15 column too.

so is this library has limit up to 15 column? thanks..

**Comment by evrencoskun** [comment]
Please check #30
