### ISSUE TITLE
TableView inside BottomSheet not scrolling

### ISSUE THREAD

**Issue by jck9007** [evrencoskun/TableView#226]
Hi, it's the first time I use TableView and I'm really liking it!
 
However I'm having some troubles with vertical scrolling, I'm using TableView inside a BottomSheet.
I had the same issue adding a ListView inside BottomSheet, but I solved it by adding a setOnTouchListener and disabling the BottomSheet scrolling when scrolling the ListView.

¿How can I do something like this on TableView? If I add setOnTouchListener to TableView it does not get called.

This is displayed in console each time I try to scroll:

W/CellRecyclerView: mIsVerticalScrollListenerRemoved has been tried to add itself before remove the old one
D/VerticalRecyclerViewListener: mCellRecyclerView scroll listener added
D/HorizontalRecyclerViewListener: Scroll listener  has been added to 1 at action down
D/HorizontalRecyclerViewListener: Scroll listener  has been removed to 1 at action cancel

Thank you.

**Comment by evrencoskun** [comment]
Hi @jck9007  

It's probably because of nested scrolling process of recyclerview. Check [this](https://stackoverflow.com/questions/43871163/recyclerview-horizontal-nested-in-bottomsheet-preventing-vertical-scrolling).

There are also several dublicate issues about that  #104 , #79

**Comment by jck9007** [comment]
You're right that really helped!

Thank you!
