### ISSUE TITLE
Çoklu seçim

### ISSUE THREAD

**Issue by cansuvtek** [evrencoskun/TableView#23]
Merhaba,

Tableview projenizde çoklu seçim var mıdır acaba? yada yapılabilir mi?

**Comment by evrencoskun** [comment]
Unutmadan belirteyim, Cell'lerin _recycled_ olduğu durumda da bir takım işlemler yapman gerekecek.  

Örneğin, bir cell'in selection state'ini yada backcolor'ını, bu yardımcı method'lar il değiştirdini varsayalım.
Ancak scroll' ettiğin aşamada, o değiştirdiğin cell view holder, başka bir cell' in gösterimi için kullanılacağından dolayı.

[Bu işlemi anlatan görsel ](https://developer.xamarin.com/guides/android/user_interface/layouts/recycler-view/Images/04-view-recycling.png)

Selected olmayan bir cell de de o görünüm devam etmiş olacak. Bu yüzden, bir cell view holder'ı görüntülenmeden önce, selected olup olmadığını kontrol etmen ve ona göre, state'ini ve backcolor'ını vs. değiştirmen gerekiyor.
