### ISSUE TITLE
mCellRecyclerView is null crash while starting demo app

### ISSUE THREAD

**Issue by vladbph** [evrencoskun/TableView#259]
public CellLayoutManager()
        this.mCellRecyclerView = tableView.getCellRecyclerView();
gets null, because tableView did not set it yet. 

You either don't do prefetch in TableView.initialize() or do this:
        // CellRecyclerView recyclerView = new CellRecyclerView(getContext());
        mCellRecyclerView = new CellRecyclerView(getContext());

**Comment by MGaetan89** [comment]
I think this is a duplicate of #245.
I have suggested a fix for this in #247.

**Comment by MGaetan89** [comment]
The fix has been merged to master.
Can you close this issue if the sample app now works for you?

**Comment by MGaetan89** [comment]
@vladbph did you have a chance to check if the crash is fixed for you in master?

**Comment by vladbph** [comment]
yes, sorry for late reply. All good now.

**Comment by vladbph** [comment]
works now
