### ISSUE TITLE
the demo can`t use

### ISSUE THREAD

**Issue by csbz17027** [evrencoskun/TableView#266]
Why I run the demo the page only show first row header and single column?
![WechatIMG403](https://user-images.githubusercontent.com/11520933/69214842-01715200-0ba3-11ea-9d24-0562164cb1f7.jpeg)

**Comment by evrencoskun** [comment]
Hi @csbz17027, 

I'm also facing the same issue. 
It seems demo app doesn't work as we expected after merging some of the pull requests. 

Please move a working branch backwards in git. 
The branch whose comment is "Migrate to AndroidX" seems working to me.

**Comment by csbz17027** [comment]
Thanks for your answer @evrencoskun 
I found when I use it by gradle that work fine.
Maybe it's related to the AndroidX.

**Comment by MGaetan89** [comment]
I submitted a fix for this issue in #268.
Sorry for the mistake.
