### ISSUE TITLE
scrollToRowPosition

### ISSUE THREAD

**Issue by csbz17027** [evrencoskun/TableView#267]
Hi,
I'm in trouble when use the method of "scrollToRowPosition"
like this:
![WechatIMG404](https://user-images.githubusercontent.com/11520933/69393673-cabb4900-0d14-11ea-9fdf-0f8b20fb7d9b.jpeg)
I want to scroll 9:00(the index is 12),the  right index of cellRecyclerView in the top but the right index of rowHeaderRecyclerView in the bottom.

**Comment by evrencoskun** [comment]
Hi @csbz17027,

Sorry but, I didn't get your problem. 
BTW, your TableView looks pretty cool :)

**Comment by csbz17027** [comment]
@evrencoskun Thanks for your reply.
I have found the cause of the problem.
Beacause I setMargin with mRowHeaderRecyclerView.
Finally,thanks a lot for this library :）
