### ISSUE TITLE
Error:(53, 69) error: cannot find symbol variable m_jContext where C is a type-variable: C extends Object declared in class CellRecyclerViewAdapter

### ISSUE THREAD

**Issue by Xack21** [evrencoskun/TableView#27]
Error:(53, 69) error: cannot find symbol variable m_jContext
where C is a type-variable:
C extends Object declared in class CellRecyclerViewAdapter

////////////////////////////////////////////////////////

Error:(99, 37) error: cannot find symbol variable m_jItemList
where C is a type-variable:
C extends Object declared in class CellRecyclerViewAdapter

**Comment by evrencoskun** [comment]
I have been refactoring all codes to get rid of hungary notation code style on TableView for 2 days. Some of changed codes is not commited yet on github. 

So, that's why you get this problem that is not big deal.

**Comment by Xack21** [comment]
First of all thanks for reply.
Actually I m beginner level Android developer..
So, how do i resolve that issue?

**Comment by evrencoskun** [comment]
Hi @Xack21, 

If you want to use TableView on your project, than you don't need to add TableView source codes to the your project if you don't need any addition feature for your TableView. 

Then you can add the library  to your project the following dependency into your `build.gradle` like this;

```java
dependencies {
 compile 'com.evrencoskun.library:tableview:0.8.5.4' 
}
```

You can also check [build.gradle](https://github.com/evrencoskun/TableViewSampleApp/blob/master/app/build.gradle) file of [the sample app ](https://github.com/evrencoskun/TableViewSampleApp)


By the way, if you want to use sources of The TableView, 

you can change `m_jContext `to `parent.getContext();`

**Comment by Xack21** [comment]
Thanks a lot...Brother 👍
