### ISSUE TITLE
The removed allowBackup attribute

### ISSUE THREAD

**Issue by FioneraGH** [evrencoskun/TableView#278]
Need a release to avoid sync project error.

9d76e4cf34a53f2a70d0604ef7a7b1bfbd259208

**Comment by MGaetan89** [comment]
Until it is released, you should be able to ignore the error by adding `tools:replace="android:allowBackup"` on the `<application>` tag in your `AndroidManifest.xml` file.

**Comment by FioneraGH** [comment]
Another one has the attribute too, just an error in IDE Gradle Sync.

**Comment by MGaetan89** [comment]
@evrencoskun Version 0.8.9 still doesn't seem to have been released: https://mvnrepository.com/artifact/com.evrencoskun.library/tableview?repo=spring-libs-milestone
Any news on this?

**Comment by FioneraGH** [comment]
> @evrencoskun Version 0.8.9 still doesn't seem to have been released: https://mvnrepository.com/artifact/com.evrencoskun.library/tableview?repo=spring-libs-milestone
> Any news on this?

https://jcenter.bintray.com/com/evrencoskun/library/tableview/0.8.9/

**Comment by MGaetan89** [comment]
Oh didn't think to check there, thanks.
So I guess this issue can be closed now?

**Comment by FioneraGH** [comment]
Close
