### ISSUE TITLE
Hide columns

### ISSUE THREAD

**Issue by theapache64** [evrencoskun/TableView#28]
Is there any method available to hide columns?

**Comment by evrencoskun** [comment]
Maybe in the future, but the latest version does not support this feature.

**Comment by theapache64** [comment]
It's okay. bro. By the way, Good work. Keep it up (y) :smile:

**Comment by evrencoskun** [comment]
Thanks

**Comment by theapache64** [comment]
I've implemented this feature here. #29 and created a pull request.

**Comment by evrencoskun** [comment]
Hi @theapache64, 

0.8.5.5 version which can show and hide the column, has been just relased. You can use [the helper methods ](https://github.com/evrencoskun/TableView#hiding--showing-the-column)for your needs.

Have a nice day.
