### ISSUE TITLE
onCellClicked start new Activity

### ISSUE THREAD

**Issue by sanakalam** [evrencoskun/TableView#283]
```
Intent myIntent = new Intent(needSomeContext, LoanTransaction.class);
                startActivity(myIntent);
```
I want to start new activity on cell clicked. But context get issue.

**Comment by evrencoskun** [comment]
Hi @sanakalam 
I don't get the issue. Could you please explain your problem? 

I'd recommend you check [the listener](https://github.com/evrencoskun/TableView/blob/master/app/src/main/java/com/evrencoskun/tableviewsample/tableview/TableViewListener.java) class of the sample app.

**Comment by sanakalam** [comment]
I was facing an issue when I want to change activity on cell click. 
I use the below code to resolve it.
Intent intent=new Intent(mContext,LoanTransaction.class);
mContext.startActivity(intent);
