### ISSUE TITLE
how to make it work with CoordinatorLayout

### ISSUE THREAD

**Issue by spd-heshuip** [evrencoskun/TableView#3]
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.design.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:background="@color/cell_line_color">

    <android.support.design.widget.AppBarLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">


        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="200dp"
            app:layout_scrollFlags="scroll|enterAlways|enterAlwaysCollapsed"
            >

        </FrameLayout>

        <android.support.design.widget.TabLayout
            android:id="@+id/tabLayout"
            android:layout_width="match_parent"
            android:layout_height="45dp"
            android:background="#ffffff"
            />

    </android.support.design.widget.AppBarLayout>

    <android.support.v4.view.ViewPager
        android:id="@+id/viewpager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_behavior="@string/appbar_scrolling_view_behavior"
        >

    </android.support.v4.view.ViewPager>

</android.support.design.widget.CoordinatorLayout>
```

HI,this is my layout file ,I put the TableView on the fragment,and fragment was added to the ViewPager,now I want to hide the FrameLayout which in the CoordinatorLayout,when scroll the TableView,but it is not work .so what should I do to solve this problem?please help me,Thanks you very much!

**Comment by evrencoskun** [comment]
Hi there,  
I haven't tried your test case. But I can give a suggestion.

Please try this;

```
tableView.getRowHeaderRecyclerView().setNestedScrollingEnabled(true);
tableView.getCellRecyclerView().setNestedScrollingEnabled(true);
```

**Comment by spd-heshuip** [comment]
I  have solved this problem,the way is same as your suggestion,Thanks!
And there is another question,I use TableView in the fragment,and init that in the onActivityCreated Method, when I first Scroll the TableView ,the Column Header Item will shake(maybe it has redraw I think),but when I init the TableView in the onCreateView method,it is woking ok. I don't know the reason.Can you tell me?

**Comment by spd-heshuip** [comment]
I have solved this problem,the way is same as your suggestion,Thanks!
and there is another question,i use the TableView in the fragment which was added to the ViewPager,and init the TableView when the fragment is visible(lazy load),when I first scroll the TableView,the Column header will shake(I think it is redraw),how should I do to solve this problem?

**Comment by evrencoskun** [comment]
I am glad that your problem has been solved. Now I am closing the issue.

Please open a new one  to your 2. question to be orderly.

Thanks
