### ISSUE TITLE
Tableview Example App Data Model inconsistency

### ISSUE THREAD

**Issue by Zardozz** [evrencoskun/TableView#303]
In  https://github.com/evrencoskun/TableView/blob/master/app/src/main/java/com/evrencoskun/tableviewsample/tableview/model/Cell.java

The constructor takes an `Object` type for it's constructor for the `data` variable but the `setData` method only takes a `String` type Object to update the data in this Data Model.

This has no affect on the Example App, but as an example of a Data Model implementation it is not consistent.

Suggest that the `setData` method be changed to:-

```java
public void setData(@Nullable Object data) {
        mData = data;
    }
```

(Sorry this is not worth doing a PR for a one word change)

**Comment by evrencoskun** [comment]
Thanks, @Zardozz, it seems to be overlooked.
