### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by Zardozz** [evrencoskun/TableView#304]
I recently tried to follow the documentation to use this library and felt that it needed some improvement as I had to hunt around in the source code of the 2 sample apps and the library itself to make a working demo app.

A list of improvement and the reason is below (A git diff patch file of the actual changes attached as you cannot fork the Wiki Git to provide a pull request) :-

1. File "1.-Getting-Started.md"  
Add the compileOptions for Java 1.8 to allow the support of running on Android lower than API 26, these are not set by default by AndroidStudio and if you don't set them you will get a build error of:-
> Invoke-customs are only supported starting with Android O (--min-api 26)

2. File "Home.md"  
Add a Feature statement about Android API support level, this useful information for users and contributors (I guess this would be Android API 14 and above)

3. File "1.-Getting-Started.md"  
Add the dependency on RecyclerView (Min version taken from Sample App)

4. File "1.-Getting-Started.md"  
Change the `compile` dependency statement to `implementation`

5. File 1.2.-Creating-a--Adapter.md  
The lists that are referenced could be confused with actual extended `ViewModal` classes which they are not, so a better name I think is "Data Objects"
>  ```AbstractTableAdapter``` class requires 3 different lists which represent respectively; **ColumnHeader**, **RowHeader** and **Cell** ViewModels.  

6. File 1.2.-Creating-a--Adapter.md  
Not enough is done to explain the **ColumnHeader**, **RowHeader** and **Cell** Classes needed, this should be before creating the adapter.  
Nothing is done to explain the Column, Row, Cell and Corner layouts needed by the adapter.  
So rename  `1.2.-Creating-a--Adapter.md` to `1.4.-Creating-a-Adapter.md` and so on to allow for new sections explaining these items.

7. New File 1.2.-Creating-Data-Models.md  
Explain creating a basic set of data models.

8. New File 1.3.-Creating-Layouts.md  
Explain creating a basic set of layouts that match the example adapter.

9. File 1.4.-Creating-a--Adapter.md  
Various typo's fixed and matched to the example layouts including dynamically completing the column widths as this is I feel a fundamental feature.

10. File 1.5.-Setting-the-Adapter.md  
Tweaks to explaining the lists needed and what data is needed for the example adapter.

[git-diff.txt](https://github.com/evrencoskun/TableView/files/4432376/git-diff.txt)

**Comment by evrencoskun** [comment]
Thanks @Zardozz, I've updated!
