### ISSUE TITLE
Fragment içerisinde başka framelayout açılımı ? 

### ISSUE THREAD

**Issue by cansuvtek** [evrencoskun/TableView#31]
Merhabalar, 
Buton click olayı ile açılmasını istediğim sayfa bir fragment ve layout kısmında ayrı bir framelayout a sahibim.

Açılan sayfada doldurulması gereken yerler ve ona göre dolan bir grid görseli olacak.

Şimdi yaptığınız tableview yapısında activity sayfasından bir fragment çağırılmış.

Kendi projeme uyarlayamadım çünkü benim bir tane activity sayfam var sonrasındaki sayfa ilerlemelerim fragment ile bunun üzerine yine bir fragment ten başka fragment a geçtiğim sayfamın görselinde grid e ayırdığım kısmın(framelayout) tableview görseli ile açılması için ne yapabilirim?

-  ilk yönlendirmeyi hangi sayfadan verebilirim?(Acticity-Fragment)

Not:Tableview kendi projemde bir grid yapısıdır.

**Comment by evrencoskun** [comment]
Selam Cansu,

Yazdıklarından hiç bir şey anlamamakla birlikte, sana gönül rahatlığıyla söylebilirim ki;  yaşadığın sorun, TableView ile alakalı değil :)

Kolay gelsin.

**Comment by cansuvtek** [comment]
Teşekkürler ={
