### ISSUE TITLE
License inconsistency 

### ISSUE THREAD

**Issue by Zardozz** [evrencoskun/TableView#310]
At the moment is seems this library seems to be licensed under no license, Apache 2 or MIT

JCenter currently lists the license for this package as "Apache 2.0 which does not match the contents of LICENSE FILE https://github.com/evrencoskun/TableView/blob/master/LICENSE
See https://bintray.com/evrencoskun/maven/tableview  
This is because the `com.novoda.bintray-release` plugin defaults everything to Apache 2

Also Gradle/Maven/Ivy could just get the pom and aar files and there would be no license information

There are also various tools from Google and other available that inspect the Maven Pom file for details including License Details.

At the moment the generated Pom file for this project is the bare minimum.
e.g. see https://dl.bintray.com/evrencoskun/maven/com/evrencoskun/library/tableview/0.8.9.2/:tableview-0.8.9.2.pom

I have made the following Pull Request   ###To make the license info consistent across various places that it should be stored 

This sets a License in the bintray-release publish settings in the build.gradle

It seems that bintray-release plugin has a mechanism for including extra details in the pom.xml file BUT this seems out of date and is targeted at only Java Packaging not Android Packaging. It also replaces the default pom.xml with a new one missing details.  
So I've used parts of it and details in various defects against the plugin to add the right license xml to the exiting generated pom.xml for Android. 

The Pom generated by running `gradlew bintrayUpload -PbintrayUser=BINTRAY_USERNAME -PbintrayKey=BINTRAY_KEY -PdryRun=true -console verbose`  
in to the Maven cache correctly validates against the Maven Pom Schema

The output of the dryrun is

`> Task :tableview:generatePomFileForReleasePublication
Updating pom-file(s) with License info

> Task :tableview:bintrayUpload
Uploading to https://api.bintray.com/content/evrencoskun/maven/tableview/0.8.9.3/com/evrencoskun/library/tableview/0.8.9.3/tableview-0.8.9.3-sources.jar...
Uploading to https://api.bintray.com/content/evrencoskun/maven/tableview/0.8.9.3/com/evrencoskun/library/tableview/0.8.9.3/tableview-0.8.9.3-javadoc.jar...
Uploading to https://api.bintray.com/content/evrencoskun/maven/tableview/0.8.9.3/com/evrencoskun/library/tableview/0.8.9.3/tableview-0.8.9.3.aar...
Uploading to https://api.bintray.com/content/evrencoskun/maven/tableview/0.8.9.3/com/evrencoskun/library/tableview/0.8.9.3/tableview-0.8.9.3.pom...

BUILD SUCCESSFUL in 2s
28 actionable tasks: 4 executed, 24 up-to-date
`

Pull Request #309

**Comment by MGaetan89** [comment]
The PR was merged. Can you close this issue?

**Comment by Zardozz** [comment]
I would love to close this but it has not been released, so checking of the License JCenter displays cannot be done

**Comment by Zardozz** [comment]
This can be closed, while JCenter/bintray web view still has the wrong license, this is not important (especially as this repository is closing down soon), the POM file https://dl.bintray.com/evrencoskun/maven/com/evrencoskun/library/tableview/0.8.9.4/tableview-0.8.9.4.pom show a correct license which is important.
Obviously when the library is migrated to it's new publish location this will have to be redone (this is easy to do with Maven Central Publishing)
