### ISSUE TITLE
TableView.setTableViewListener() Not Working in version 0.8.9.2

### ISSUE THREAD

**Issue by antoniomerlin** [evrencoskun/TableView#318]
In latest release of TableView library the tableview listener is not working. i've checked with previous release.

**Comment by sudaniprashant** [comment]
this should fix

app:allow_click_inside_cell="true"
app:allow_click_inside_column_header="true"
app:allow_click_inside_row_header="true"

attributes says it all, use accordingly

**Comment by antoniomerlin** [comment]
Thanks forgot to view in attributes changes, just looked in project wiki.
