### ISSUE TITLE
Add onRowClicked function for ITableViewListener.

### ISSUE THREAD

**Issue by baiguangyuan** [evrencoskun/TableView#32]
Function onRowClicked just like onItemClick of ListView.
thanks

**Comment by evrencoskun** [comment]
Hi @baiguangyuan , 

I really don't get what exacly you need. 


ITableViewListener has already has [a function](https://github.com/evrencoskun/TableView#4-set-click-listener-to-the-tableview) like you want. 

```java
 /**
     * Called when user click any Row Header item.
     *
     * @param rowHeaderView : Clicked Row Header ViewHolder.
     * @param rowPosition     : Y (Row) position of Clicked Row Header item.
     */
    @Override
    public void onRowHeaderClicked(@NonNull RecyclerView.ViewHolder rowHeaderView, int
            rowPosition) {
        // Do what you want.

    }
```

**Comment by baiguangyuan** [comment]
I want to use it to show stock list. when click any row push to stock chart activity. 
How can I do?  

<img width="624" alt="stock" src="https://user-images.githubusercontent.com/4171013/35655816-cd04ba18-072e-11e8-8241-a4c2c104da87.png">
thanks

**Comment by baiguangyuan** [comment]
I get it. Thanks.
