### ISSUE TITLE
Cell Width resize issue.

### ISSUE THREAD

**Issue by shiva-kumar-R** [evrencoskun/TableView#320]

**Comment by u-barnwal** [comment]
Was the width of your table changing terribly on scroll? If yes, did you find the solution?

**Comment by ReejeshPK** [comment]
If you look inside the **CellViewHolder** in the sample app, you will find these two lines :

// It is necessary to remeasure itself.
```
        cell_container.getLayoutParams().width = LinearLayout.LayoutParams.WRAP_CONTENT;
        cell_textview.requestLayout();
```

Putting these lines inside the onBindCellViewHolder, onBindColumnHeaderViewHolder helped solve the issue.

_cell_container_ is the parent layout of your cell.

I kind of put it in all onBind

Here is the file : https://github.com/evrencoskun/TableView/blob/master/app/src/main/java/com/evrencoskun/tableviewsample/tableview/holder/CellViewHolder.java

**Comment by IlhamHadisyahRamadhani** [comment]
still having this issue after added 
`cellContainerView.layoutParams.width = xxx`
`cellCcontainerView.requestLayout()`. 

and

`headerContainerView.layoutParams.width = xxx`
`headerCcontainerView.requestLayout()`. 

all of these located on 
`onBindCellViewHolder `and `onBindColumnHeaderViewHolder`

condition : 
- I have 4 adapter and 1 tableView, the adapter will changed on each filter triggered by spinner
- on each adapter has different colWidth
- changing adapter using tableView.adapter = adapter1 / adapter2 and so on.

issue : 
- if the first time I select filter1 with adapter1, the width is normal, then I select filter 2 with adapter 2,  the width is resized (some cell have same width with the adapter 1).
- if the first time I select filter2 with adapter2, the width is normal, then I select filter 1 with adapter 1,  the width is resized (some cell have same width with the adapter 2).
- and so on.
