### ISSUE TITLE
cell color not set

### ISSUE THREAD

**Issue by umeshkanhasoft** [evrencoskun/TableView#335]
@Override
    public void onBindCellViewHolder(@NonNull AbstractViewHolder holder, @Nullable Cell cellItemModel, int columnPosition, int rowPosition) {
        ((CellViewHolder) holder).cellData.setText(((Cell) cellItemModel).getData());
        ((CellViewHolder) holder).setBackgroundColor(ContextCompat.getColor(context,R.color.colorAccent));
     }

**Comment by ashish-dhiman-net** [comment]
Hi @umeshkanhasoft 
I was able to change background color of my header using:

`onBindColumnHeaderViewHolder

try {
            columnHeaderViewHolder.itemView.getBackground().setColorFilter(Color.parseColor(columnHeaderItemModel.getColor()), PorterDuff.Mode.DARKEN);
        } catch (Exception e) {
            e.printStackTrace();
        }
`

**Comment by umeshkanhasoft** [comment]
thanks
