### ISSUE TITLE
ClickListener can not respond to click events correctly

### ISSUE THREAD

**Issue by Joker-zou** [evrencoskun/TableView#346]
Hi, I have some trouble in clicklistener,it seems to can not respond to click events correctly in the newest version(0.8.9.2).

The code in constructor can be run，but code in all listeners like onCellClicked,onColumnHeaderClicked and other of them will do nothing. Just like this
`public MyTableViewListener(Context context){
        this.context = context;
        //can run
        Toast.makeText(context, "entry listener", Toast.LENGTH_SHORT).show();
    }
    @Override
    public void onCellClicked(@NonNull RecyclerView.ViewHolder cellView, int columnPosition, int
            rowPosition) {
        //can not run
        Toast.makeText(context, "click", Toast.LENGTH_SHORT).show();
    }`

But I notice that another older version can correctly response all click events. (about  10/2017)

So I don't know if I'm using it the wrong way,can you help me solve this problem? thanks~

**Comment by spencerhowell** [comment]
I am having a similar issue, but only with `onCellClicked`. `onColumnHeaderClicked` and `onRowHeaderClicked` are working as expected.

**Comment by sajaljain** [comment]
@spencerhowell I am facing similar issue, @evrencoskun please suggest from work around

**Comment by MGaetan89** [comment]
@Joker-zou @spencerhowell @sajaljain if I remember correctly, there was a change of behaviour introduced in version 0.8.9.2.
Can you try to add any of these on your `TableView` to see if it works:
```xml
app:allow_click_inside_cell="true"
app:allow_click_inside_row_header="true"
app:allow_click_inside_column_header="true"
```

**Comment by gaochuntie** [comment]
> @Joker-zou @spencerhowell @sajaljain if I remember correctly, there was a change of behaviour introduced in version 0.8.9.2. Can you try to add any of these on your `TableView` to see if it works:
> 
> ```
> app:allow_click_inside_cell="true"
> app:allow_click_inside_row_header="true"
> app:allow_click_inside_column_header="true"
> ```

Yes,it works
