### ISSUE TITLE
Unable to install library in my android project

### ISSUE THREAD

**Issue by levosoft** [evrencoskun/TableView#349]
Hi @evrencoskun!

Your project is very cool, but unfortunatly I can't install it to my project in Android Studio, by your Wiki page. ("Getting Started")

`dependencies {`
`implementation 'com.evrencoskun.library:tableview:0.8.9.2'`
`implementation 'androidx.recyclerview:recyclerview:1.1.0'` 
 `}`

I receive this message, after I try syncing gradle:
"**Failed to resolve: com.evrencoskun.library:tableview:0.8.9.2**"

Please help me!

**Comment by Zardozz** [comment]
The docs look wrong, I successful use

`implementation 'com.evrencoskun.tableview:0.8.9.2'`

As it is published at https://bintray.com/beta/#/evrencoskun/maven/tableview/0.8.9.2?tab=overview

**Comment by levosoft** [comment]
Thank you @Zardozz !
Now it works fine!
Yes, the missing jcenter was the problem...
