### ISSUE TITLE
TableView cell selection not working ie not changing background color or text color upon selection

### ISSUE THREAD

**Issue by ALAUDDIN-PIAL** [evrencoskun/TableView#350]
app:selected_color="@color/selected_background_color"
not working on xml

**Comment by HarshSuvagiya** [comment]
make sure you had added this line in your xml

`  android:layout_width="match_parent"  ` as

`    <com.evrencoskun.tableview.TableView
        android:id="@+id/tableView"
        android:layout_width="match_parent"
        app:allow_click_inside_cell="true"/>
`
