### ISSUE TITLE
Row header should be part of the Dataset and be sortable

### ISSUE THREAD

**Issue by sonique6784** [evrencoskun/TableView#38]
Hi, 
thanks for this awesome library. However, I believe Row Header should be sortable, cause most of the time the first column of a dataset is the actual row header.

**Comment by evrencoskun** [comment]
Hi @sonique6784,

I distinguish between each other to support further use. 
For example; You don't have to show index of row on row header. 

![24 0_7-bootstrap-table-checkbox](https://user-images.githubusercontent.com/4228262/35721902-45d9eb9e-0805-11e8-8b6f-eeae8daf33ef.jpg)

In my opinion, keeping datasets independent of each other, also offers a better approach to features that will be added in the future. 


Thank you for your comment, I will review this topic again.

**Comment by sonique6784** [comment]
fixed with #49
