### ISSUE TITLE
the Column header will shake

### ISSUE THREAD

**Issue by spd-heshuip** [evrencoskun/TableView#4]
I use the TableView in the fragment which was added to the ViewPager,and init the TableView when the fragment is visible(lazy load),when I first scroll the TableView,the Column header will shake(I think it is redraw),how should I do to solve this problem?

**Comment by evrencoskun** [comment]
Hi, Have you used the latest version ? And to be more clear please share some screenshots ( video would be much better)

**Comment by spd-heshuip** [comment]
I use the version is 0.8.2,and this is the video,Thanks!

[QQ20171121-143402-HD.mp4.zip](https://github.com/evrencoskun/TableView/files/1490292/QQ20171121-143402-HD.mp4.zip)

**Comment by evrencoskun** [comment]
It seems width value of the colum header doesn't calculated right for the first time. When you scroll up, tableView controls & sets the right width values. 


On your TableViewAdapter, do you have  like the below lines ?. 

  ```
      // It is necessary to remeasure itself.
        columnHeaderViewHolder.column_header_container.getLayoutParams().width = LinearLayout
                .LayoutParams.WRAP_CONTENT;
        columnHeaderViewHolder.column_header_textview.requestLayout();
  ```
this is from [sample app](https://github.com/evrencoskun/TableView/blob/master/app/src/main/java/com/evrencoskun/tableviewsample/tableview/TableViewAdapter.java) 


If you already have, you may use the below code on   onPageSelected function of your PageChangeListener.

`tableView.getColumnHeaderLayoutManager().customRequestLayout();`

**Comment by spd-heshuip** [comment]
it is working good,Thanks you very much!
