### ISSUE TITLE
Pagination feature

### ISSUE THREAD

**Issue by jeremy-ingenuity** [evrencoskun/TableView#40]
Hi I would like to share this feature that I am currently working on for the TableView which is pagination, currently the pagination works fine for basic data loading, but I still continue to fix conflicting issues with sorting and filtering.

### NOTES:
- I added a Listener interface for the AbstractTableAdapter which notifies when any changes on row, column and cell items occurs. I will also update the filtering implementation to use the listener instead of storing the original data into another class. Don't worry, I didn't change any of your code/implementation of the TableView, I only added extensions.
- I will not submit a PR yet unless sorting and filtering issues are resolved.
#### Functional:
- Pagination on standalone data loading, meaning dataset is not modified yet by sorting or filtering.
- Go to page functionality.
- Loading next and previous pages.
- Loading number of items per page which can be set.
#### Bugs:
- Sorting and filtering conflicts.
- No retention of sorting and filtering on pagination actions, any filter or sorting is lost on page changing.
- Filtering only applies to current page.
- Sorting only applies to current page.
- Many more...

<img src="https://user-images.githubusercontent.com/35909930/35776681-ebbcbb68-09db-11e8-941c-aaa5a5fbac64.gif" width="270" height="480">

**Comment by evrencoskun** [comment]
Thank you @jeremy-ingenuity, 

I haven't finished to review the changes. But there are some wrong usages on your codes that may cause some bugs that you listed. And I've noted for you. 

As soon as the review process is over, I will share the notes to you on github.

However, the process will not be done today because of my busy schedule. So, that would be great to release the new version next week. Thus, we may fix the bugs during this time. 

Have a nice weekend

**Comment by jeremy-ingenuity** [comment]
I have an updated preview here with the implemented number of items to be displayed per page.
<img src="https://user-images.githubusercontent.com/35909930/35777194-9c6dd67e-09e4-11e8-831d-32d2d32e503b.gif" width="270" height="480">

@evrencoskun Thank you! I'll continue to improve this if I also have free time. It's okay, no pressure man. Have a nice weekend also.

**Comment by sonique6784** [comment]
@jeremy-ingenuity, I've reworked sorting recently and moved the sorting state into the Column Header Cell (was in the recycler before), this might fix some issues, like the retention.

**Comment by evrencoskun** [comment]
Hi @jeremy-ingenuity ,

0.8.6 version which has got paging and filtering functionallies,  has been released. I have also updated the README. However, these topics need more explanations for developers. 

For example; the steps to implement these functions would be very useful for developers like [sorting topic](https://github.com/evrencoskun/TableView#sorting)

Thank you 👍

**Comment by jeremy-ingenuity** [comment]
Hi @evrencoskun , good day! Thanks for the update. Don't worry, I will help in providing comprehensive documentation and implementation updates for the features of the TableView. I will help update the README and submit a PR when I have free time.

**Comment by evrencoskun** [comment]
Perfect :) 

Have a nice day
