### ISSUE TITLE
while building -Failed to resolve: com.evrencoskun.library:tableview:0.8.9.4

### ISSUE THREAD

**Issue by ThreeMinutesFix** [evrencoskun/TableView#408]
**Describe the bug**
While  adding lib to android app using dependency - I receive -> Failed to resolve: com.evrencoskun.library:tableview:0.8.9.4

**Expected behavior**
BUILD SUCCESSFUL in 722ms

**Screenshots**
https://ibb.co/yWXZmBW

**Stacktrace**
If applicable, add the stacktrace you encountered.

**Tools:**
 - `TableView` version: [v0.8.9.4]
 - Android version: [12]
 - Studio version :[ 2022.2.1 Patch 2]

**Additional context**
It was working fine till today afternoon

**Comment by Lanfr** [comment]
I had the same problem.  How did you solve it

**Comment by ThreeMinutesFix** [comment]
after rebuilding and invalidate cache i restarted my pc once and its start to work. also to be added this issue is like varies from system to system my pc does not shows any error but my laptop it shows error

**Comment by zhazha208** [comment]
implementation 'com.github.evrencoskun:TableView:v0.8.9.4'
