### ISSUE TITLE
Cell onCellLongPressed

### ISSUE THREAD

**Issue by frknkntr** [evrencoskun/TableView#45]
Merhaba, satır ve sütunda bulunan "on..LongPressed" metodu, hücrede aktif değil (yada ben göremedim). Bu konuyu nasıl halledebilirim?

**Comment by evrencoskun** [comment]
Selam Furkan,

Evet. ITableViewListener içerisinde cell'e ait bir longPress methodu yok. Bunun sebebi, tabloyu scroll ederken de, uzun basma aksiyonunun tetikmelesi. 

Özetle, stabil olmadığından, o methodu yayınlamadım. 

> Bu konuyu nasıl halledebilirim?

Cell'lerin ViewHolder'ını yaratma aşamasında, onlara OnLongClickListener set edebilirsin.

**Comment by frknkntr** [comment]
Cevap için çok teşekkürler, iyi çalışmalar.

**Comment by evrencoskun** [comment]
Selam Furkan, 

Bu özelliğe sahip 0.8.6 versiyon çıktı.
