### ISSUE TITLE
Support API below 21 

### ISSUE THREAD

**Issue by abolfazlrma** [evrencoskun/TableView#5]
I think for support widely Android devices it will be very great to manipulate or extends your beautiful ,new and useful table view to support API+15, and as question ,Is it in your plan and if yes when?

**Comment by evrencoskun** [comment]
Thank you for your words. 
I have just updated the source code to be able to support this feature. 
I have just tested a device that has a 16 build version, It works as we expected. 

This weekend, I'll publish a new version that is 0.8.4. The feature will be in this version as well.

**Comment by abolfazlrma** [comment]
thanks a lot. good luck.

**Comment by abolfazlrma** [comment]
thanks a lot big man, Good Luck.

**Comment by evrencoskun** [comment]
0.8.3. version has been just published.

**Comment by abolfazlrma** [comment]
thanks a lot,

Good luck...
