### ISSUE TITLE
Using different view widgets

### ISSUE THREAD

**Issue by ddk9499** [evrencoskun/TableView#58]
Hi! How to use different Views in one table?
In the example below, in **Student name** column, i want to use TextView, but in **Score** and **Comment** i want to use EditText. how to realize this? 
![image](https://user-images.githubusercontent.com/33849788/36331728-d3448106-1390-11e8-8936-afd091bb3320.png)

**Comment by jeremy-ingenuity** [comment]
Hi @ddk9499 , you can achieve that by creating a different ViewHolder for each type of cell (StudentNameViewHolder w/ TextView, ScoreViewHolder w/ EditText and CommentViewHolder w/ EditText), see #41 for the answer. Hope it helps.
