### ISSUE TITLE
Background Color does not change despite i set it for cell layout

### ISSUE THREAD

**Issue by abolfazlrma** [evrencoskun/TableView#6]
Hi dear,
i set a color in cell layout for background but when i run it is still  white?

**Comment by evrencoskun** [comment]
You need to set a TableView listener to be able to show your cell background color. Actually, It's a bug and it wouldn't be necessary. By the way, I have already fixed this problem. This weekend, I will be published new release. And it will be got this fix as well.

**Comment by abolfazlrma** [comment]
thanks man , as soon as possible.
