### ISSUE TITLE
How to reduce the size of corner layout?

### ISSUE THREAD

**Issue by abhinav011085** [evrencoskun/TableView#65]

**Comment by evrencoskun** [comment]
Hi @abhinav011085,

I am not sure, I understand you clearly.  The below graph provides the structure of TableView. Considering this graph, you can ask your question. 

![structurecrop](https://user-images.githubusercontent.com/4228262/37030026-72430a22-214a-11e8-8e42-40a132f9868e.png)

**Comment by abhinav011085** [comment]
Hey @evrencoskun , i was talking about the corner view. In my app, the size of corner view is bigger than the width and height of my row and column header, so it was showing a blank area of that extra width.

**Comment by evrencoskun** [comment]
Could you please share your xml files of corner layout, row header layout and column header layout?

**Comment by abhinav011085** [comment]
it was same as the sample app
https://github.com/evrencoskun/TableViewSampleApp/tree/master/app/src/main/res/layout

**Comment by sonique6784** [comment]
this pull request should let you do so: #57

**Comment by evrencoskun** [comment]
Hi @abhinav011085, 

In this TableViewSampleApp project, all each row header items use the same layout that is [tableview_row_header_layout](https://github.com/evrencoskun/TableViewSampleApp/blob/master/app/src/main/res/layout/tableview_row_header_layout.xml)

As you can see in this xml, the width value of the item container gets from [@dimen/table_view_row_header_width](https://github.com/evrencoskun/TableViewSampleApp/blob/master/app/src/main/res/values/dimens.xml)

If you change this value, the width value of   both of the row header recyclerview and the corner view  layer will be changed.


Beside this, If you need to change these width sizes dynamically, with @sonique6784  implementation you can do this. However, there is no any version that has the related implementation yet. So, you have to wait the next release.

**Comment by abhinav011085** [comment]
Thanks, i'll try that

**Comment by evrencoskun** [comment]
If you won't make out your problem, feel free reopen this issue.

See you.
