### ISSUE TITLE
how to pick cell value 

### ISSUE THREAD

**Issue by jitesh68** [evrencoskun/TableView#67]

**Comment by evrencoskun** [comment]
Hi @jitesh68 

There are some ways to get a cell item value.

The first way you can use is getting the value using the [getCellItem ](https://github.com/evrencoskun/TableView/blob/master/tableview/src/main/java/com/evrencoskun/tableview/adapter/AbstractTableAdapter.java) method of TableViewAdapter

```java
// It returns your cell  model value. 
tableView.getAdapter().getCellItem(int columnPosition, int rowPosition)
```

**Comment by jitesh68** [comment]
how i get values from

  @Override
    public void onCellClicked(@NonNull RecyclerView.ViewHolder cellView, int column, int row) {
        // Do what you want.
        if(column==8){
            showToast("Cell " + column + " " + row + " has been clicked.");

           

        }

    }

**Comment by jitesh68** [comment]
sorry i m beginner  need help

**Comment by evrencoskun** [comment]
Please check [this issue](https://github.com/evrencoskun/TableViewSampleApp/issues/3)
