### ISSUE TITLE
Scroll oblique (horizontal and vertical at the same time) and Scroll Performance

### ISSUE THREAD

**Issue by geoffreylzf** [evrencoskun/TableView#70]
I am very appreciate for your hardwork and it is well implemented into my work.

Is there any ways to scroll oblique (horizontal and vertical at the same time), just like below gif

> https://raw.githubusercontent.com/Cleveroad/AdaptiveTableLayout/master/images/demo.gif

I found out there is performance issue when scroll to the end , my table is (20 column x 56 row ), the table show some lag until the end, is there any way to adjust the scroll speed just like override "fling" in recycle view like the link below?

> https://stackoverflow.com/a/30747742

**Comment by evrencoskun** [comment]
Hi @geoffreylzf 

> Is there any ways to scroll oblique (horizontal and vertical at the same time), just like the gif
Nope sorry.  
![structurecrop](https://user-images.githubusercontent.com/4228262/38041936-b4562750-32bb-11e8-8ae0-255a9efaf88c.png)

As you can see the above graph, TableView has a nested RecyclerView to represent cell items.
Both CellRowRecyclerView and CellRecyclerView have a custom layout manager that is extended from LinearLayoutManager that allows scroll just vertically or horizontally.

That means, to support the feature, it needs some extra controls.

> I found out there is performance issue when scroll to the end , my table is (20 column x 56 row ), the table show some lag until the end,

Calculation each column width makes some lag. It is proportional to the number of columns shown. So If you test your case on a phone, It would provide much smoother scroll. 

>  is there any way to adjust the scroll speed just like override "fling" in recycle view like the link below?

I didn't know there is a way to change the scroll velocity of a recyclerview. I needed that when I worked on calculating column widths. Thanks for that. After that implementation, It's not perfect as you expect, but it provides just a little smoother scroll. 

I would recommend you to wait for the next version of TableView.
