### ISSUE TITLE
Column header gets cut out by white block

### ISSUE THREAD

**Issue by TheMorganHub** [evrencoskun/TableView#76]
I'm populating a TableView from a MySQL table. Everything works, except that I get this strange white cut out around the top most right corner all the time

It looks like this
![teqklno](https://user-images.githubusercontent.com/26914813/38255674-d2f189f4-3732-11e8-98de-12e0a4715c6c.png)

It doesn't happen with this small table for example
![p63m7ny](https://user-images.githubusercontent.com/26914813/38255695-e3c6f016-3732-11e8-9593-8028bbe18bb7.png)

It's odd because when I drag the column headers to the left, it does seem that the header was rendered, but that white box is cutting it out. Look at this:
As the table loads...
![cat1](https://user-images.githubusercontent.com/26914813/38255846-3e1df488-3733-11e8-9576-a92c804823c2.PNG)

When I drag the column header to the left...
![capture](https://user-images.githubusercontent.com/26914813/38255855-45227ce0-3733-11e8-8da7-8d722218e8e6.PNG)

I adapted the TableView from the sample, removed the gender and money viewholders, and instead of populating the TableView from a web service, I used a JDBC driver and queried a database.
Any idea what could be causing this? Is there a solution? (I'm using v0.8.5.1).

**Comment by TheMorganHub** [comment]
**UPDATE**
When I scroll down the table, sometimes, the column header gets fixed, but then the rows get cut out as shown in this pic
![screenshot_20180403-114241](https://user-images.githubusercontent.com/26914813/38256433-a2cb834a-3734-11e8-8baa-b2aba88638e3.jpg)

No idea why it happens.

**Comment by TheMorganHub** [comment]
**UPDATE 2**
I decided to upgrade to the latest version (0.8.6) and it seems the issue has been fixed. Sometimes, however, I do get white lines on column header like this:
![ooekyhi](https://user-images.githubusercontent.com/26914813/38257425-96f6bb50-3736-11e8-8d01-d90019289d03.png)

A workaround to fix them is to drag the TableView rows to the right and then when you drag them back to the left, you can see the lines start to disappear. I don't know what triggers this bug, because it only happens with certain tables.

**Comment by evrencoskun** [comment]
Hi @TheMorganHub 

> I decided to upgrade to the latest version (0.8.6) and it seems the issue has been fixed.

Yes, this issue might be already fixed. #24  

> A workaround to fix them is to drag the TableView rows to the right and then when you drag them back to the left, you can see the lines start to disappear. I don't know what triggers this bug, because it only happens with certain tables.

Could you please record this issue? It would be better to fix this issue.

> Another workaround is to simply scroll down the table. The lines disappear instantly. It's very odd. Any idea why it happens?

I also need a video of this case. 

By the way, Are your XML files of Column Header and Row Header view holder same with sample app? 
If there are some differences, please share your XML files too.

**Comment by TheMorganHub** [comment]
We were forced to remove the TableView from our main project after witnessing rows cutting out after sorting 😔 (this also happened on v0.8.6)
Perhaps I could try and create a new Android project and upload it to GitHub for you? Would you be OK with that?

**Comment by evrencoskun** [comment]
Sorry to hear that.

> Perhaps I could try and create a new Android project and upload it to GitHub for you? Would you be OK with that?

If it's okay for you, that would be perfect to test the case.

**Comment by TheMorganHub** [comment]
Hey again, here's the repository for you.
https://github.com/TheMorganHub/TableViewExample

The example I provide comes with a MainActivity that holds a ViewPager and TabLayout. 

The first tab is a SQL table from my server. I have granted you limited access (SELECT rights) to a sample database of mine. The database name is **sakila**. Feel free to change the target of the query to any of the SQL tables shown below. You'll find SQL Connection and account details in **TableSQLFragment.java**, as well as TableView population and handling.

![capture](https://user-images.githubusercontent.com/26914813/38439136-ecc8c310-39b2-11e8-8d4b-b5019e97e842.PNG)

The second tab is a TableView that contains randomly generated strings.
You'll find this in **TableRandomFragment.java**

I hope this proves to be useful to you and helps you fix these issues. Any questions do not hesitate to let me know.

Thank you!

**Comment by TheMorganHub** [comment]
Hey @evrencoskun 
Your solution of adding `android:background="@color/separator_color"` for my first two problems worked 😃

About the other issue...
I spent some time trying to debug the TableView using `TableViewLayoutChangeListener`. Unfortunately I couldn't find a solution, but I arrived at some conclusions.

- On the SQL tab, querying the **departments** table, your `onLayoutChange` method **works only for the first column**. If you try to sort any column that isn't the first one, the TableView breaks. It's very strange. This is the output I get when sorting the first column:

```
left 0
right 596
oldLeft 0
oldRight 546
```

```
left 0
right 596
oldLeft 0
oldRight 596
```

As you can see, the new `right` is larger than the `oldRight`. This triggers a recalculation of all children and works as expected.
Then, when I try to sort a column that isn't the first one. I get this output:

```
left 0
right 830
oldLeft 0
oldRight 830
```

For some reason, `right == oldRight`, and this fails to comply with this condition` (right - left) != (oldRight - oldLeft)`.

- I then headed to `ColumnHeaderViewHolder` class and in `onSortingStatusChanged`, I retrieved the column header RecyclerView and the Column header LayoutManager and added:

```
mCellLayoutManager.remeasureAllChild();
mColumnHeaderRecyclerView.getLayoutParams().width = WRAP_CONTENT;
mColumnHeaderRecyclerView.requestLayout();
```
I thought it'd work because that method is called every time the user sorts a column. But sadly it didn't work either.

I just made a commit to https://github.com/TheMorganHub/TableViewExample
In this commit, on the **Random** tab, I reduced the size of the generated strings and columns. This will make it easier for you to reproduce the bug.
I tried to **Descend sort** and this happens:
![capture](https://user-images.githubusercontent.com/26914813/38469947-d7d7cad8-3b32-11e8-9421-bcff4149c00a.PNG)

The bug is hit and miss and kind of unpredictable. Sometimes it happens, sometimes it doesn't, and has different results.

The random string table doesn't depend on my server, so you may use it when my server is off.

Again, thank you and I hope your figure this out 😔

**Comment by evrencoskun** [comment]
Hi @TheMorganHub ,

Sorry, my late my response. I have just found the time to test the case on your current repo. And I can clearly see the case at last. 

The remeasuring process should be done after sorting process. So, When I use the below code, 


``` java
new Handler().post(() ->
                // Recalculate of the width values of the columns
                m_iTableView.remeasureColumnWidth(mXPosition));
```

instead of this

``` java
m_iTableView.remeasureColumnWidth(mXPosition));
```
This works normal. 

![76_bug_fix](https://user-images.githubusercontent.com/4228262/38778811-bfe44542-40c7-11e8-9505-6c47c2875225.gif)

**Comment by TheMorganHub** [comment]
Hey @evrencoskun 
Thank you for your response. I implemented your solution. I assume I'm meant to add that line of code in `ColumnHeaderLongPressPopup` like this?

    ```
@Override
    public boolean onMenuItemClick(MenuItem menuItem) {
        // Note: item id is index of menu item..

        switch (menuItem.getItemId()) {
            case ASCENDING:
                m_iTableView.sortColumn(mXPosition, SortState.ASCENDING);
                break;
            case DESCENDING:
                m_iTableView.sortColumn(mXPosition, SortState.DESCENDING);
                break;
            case ROW_HIDE:
                // Hide 5. row for testing process
                // index starts from 0. That's why TEST_ROW_INDEX is 4.
                m_iTableView.hideRow(TEST_ROW_INDEX);
                break;
            case ROW_SHOW:
                // Show 5. row for testing process
                // index starts from 0. That's why TEST_ROW_INDEX is 4.
                m_iTableView.showRow(TEST_ROW_INDEX);
                break;
        }


        new Handler().post(() ->
                // Recalculate of the width values of the columns
                m_iTableView.remeasureColumnWidth(mXPosition));
        return true;
    }
```
It seems to work now, however... look what happens with the column headers after sorting. The text in them gets cut up and wrapped in two lines.

![capture](https://user-images.githubusercontent.com/26914813/38779649-a63327ec-40a1-11e8-9113-61231eeb6883.PNG)
![capture2](https://user-images.githubusercontent.com/26914813/38779650-a653d7d0-40a1-11e8-9223-e7c5790ef206.PNG)

I'm assuming this is happening because the remeasure of the column widths isn't taking into account the size of the "^" and "v" icons that appear after sorting the column.

This situation is only visible for columns with headers that are smaller than `original_width + size_of_icon`. For example, the bug doesn't happen with this column because it's larger.
![capture3](https://user-images.githubusercontent.com/26914813/38779694-318bcfce-40a2-11e8-93af-90258c26d240.PNG)

But it happened with this one because it was smaller
![capture4](https://user-images.githubusercontent.com/26914813/38779701-47de4af4-40a2-11e8-8e67-aeb2c8cdbc0c.PNG)


Again, thank you. And I'm sure we're close to fixing this for good! 😀

**Comment by evrencoskun** [comment]
@TheMorganHub 

You can set the `singleLine=true` on your column header TextView. So, It doesn't wrap the letters.

**Comment by TheMorganHub** [comment]
@evrencoskun 
I added that to `tableview_column_header_layout.xml` and now I see three dots **...** where the text should be. Is there a way for the column header to actually expand as the icon appears so this doesn't happen?

![capture](https://user-images.githubusercontent.com/26914813/38779852-949c526c-40a4-11e8-8980-5e470cd1d6d5.PNG)

**Comment by evrencoskun** [comment]
@TheMorganHub 

It's actually default behaviour of the RecyclerView. We don't do anything special for that. If your row size is long, then the moving animations won't be shown because of the performance concern. 

You can also read [the article](https://medium.com/@gabornovak/use-diffutil-for-out-of-the-box-animations-d932a28d6229), that helps to get rid of your confusion.
