### ISSUE TITLE
Crash when screen rotate

### ISSUE THREAD

**Issue by sakaravinth** [evrencoskun/TableView#77]
Hi,
Application get crashing on time of screen rotation.In sample app itself crashing.

**Comment by sonique6784** [comment]
I created a pull request to solve it #80

**Comment by evrencoskun** [comment]
Hi @sakaravinth 

please test the current repo, and let me know the result.

Thanks guys @kaminiksharma @sonique6784

**Comment by sakaravinth** [comment]
Hi All 
Its working after   removing mainFragment.onDestroy() in mainactivity.
Thanks guys @evrencoskun  @kaminiksharma @sonique6784
