### ISSUE TITLE
Fail to sync in Oreo

### ISSUE THREAD

**Issue by drkpoon** [evrencoskun/TableView#8]
Gradle file fail to sync when targeting Oreo.  Below is my build.gradle file.  The error is 'All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 26.1.0, 25.3.1. '

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.evrencoskun.library:tableview:0.8.3'
}

**Comment by evrencoskun** [comment]
Hi Derek, 

The reason is TableView has below lines.

` compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:recyclerview-v7:25.3.1'`

I think the best solution of the problem is removing this lines from TableView. I'll do that for next version. For now,  you can ignore it.

**Comment by evrencoskun** [comment]
I have just upgrade the build version to '27.0.2' which is the latest one. 

When you upgrade your support library build-version. The issue will be solved.

The new version will probably be released at the latest at the weekend. So you can test it at that time.
