### ISSUE TITLE
API Improvement

### ISSUE THREAD

**Issue by DamonChen117** [evrencoskun/TableView#82]
I have an exception 
java.lang.ClassCastException: xxxxxx.ProductStockTableAdapter$ViewHolder cannot be cast to com.evrencoskun.tableview.adapter.recyclerview.holder.AbstractViewHolder

If the ViewHolder must be the subclass of AbstractViewHolder, all the functions such as 
onCreateColumnHeaderViewHolder should return AbstractViewHolder not RecyclerView.ViewHolder

**Comment by evrencoskun** [comment]
Hi @DamonChen117,

> I have an exception
> java.lang.ClassCastException: xxxxxx.ProductStockTableAdapter$ViewHolder cannot be cast to com.evrencoskun.tableview.adapter.recyclerview.holder.AbstractViewHolder

Yes! you must extend your ViewHolder from `AbstractViewHolder `class. 

> If the ViewHolder must be the subclass of AbstractViewHolder, all the functions such as
> onCreateColumnHeaderViewHolder should return AbstractViewHolder not RecyclerView.ViewHolder

Yes! It should be.

**Comment by DamonChen117** [comment]
What I mean is that 
the interface ITableAdapter should change from

**RecyclerView.ViewHolder** onCreateColumnHeaderViewHolder(ViewGroup parent, int viewType);
to
**AbstractViewHolde**r onCreateColumnHeaderViewHolder(ViewGroup parent, int viewType);

So the error can be detected at compile time not the run time.

**Comment by evrencoskun** [comment]
@DamonChen117 I already got what you mean 👍
