### ISSUE TITLE
Column header views change background color after going offscreen

### ISSUE THREAD

**Issue by Kreiri** [evrencoskun/TableView#9]
Expectation: if table view has `setIgnoreSelectionColors(true)`, all its views should retain their background colors no matter what.

Problem: column header views change their background color permanently after going offscreen

Steps to reproduce:
1. have a table view with `setIgnoreSelectionColors(true)`;
2. have enough columns that some are offsreen;
3. scroll table view left-right
4. column header views that had been moved offscreen have now changed their background color to default "unselected color" of table view.

Why it happens: `onViewDetachedFromWindow` handler in `ColumnHeaderRecyclerViewAdapter` does not check `IsIgnoreSelectionColors()` setting of its table view when changing view's background color. Result: if a column header ever goes offscreen, its background color is changed permanently  to "unselected color".

Suggestion:  must view's background color even change on detach? It's getting changed in `onViewAttachedToWindow` handler already anyway - and with proper `IsIgnoreSelectionColors()` check, too. Same for its `selected` status.

**Comment by evrencoskun** [comment]
Hi Kreiri,

It seems I missed to add the control to the below line.

`viewHolder.setBackgroundColor(m_iTableAdapter.getTableView().getUnSelectedColor());`

Thank you for the bug report. I 'll fix this on todays version. 

Also 
> Suggestion: must view's background color even change on detach? It's getting changed in onViewAttachedToWindow handler already anyway - and with proper IsIgnoreSelectionColors() check, too. Same for its selected status.

As far as I can remember, there was necessary to do it for reused viewholders. However, I don't remember the exact case. Maybe, as you say, it's a trivial process. I need to test to find out the result without it. 

Thank you for the sugesstion. I'll take into account it.

Have a nice day.

**Comment by evrencoskun** [comment]
Hi Kreiri,

I have checked the lines. And you are right on your suggestion.

I have removed trivial lines on `CellRowRecyclerViewAdapter`, `ColumnHeaderRecyclerViewAdapter` and `RowHeaderRecyclerViewAdapter`

However, same code is necessary for `CellRecyclerViewAdapter`. Otherwise, It causes a bug that I mention above.

Anyway, thank you for your suggestion.

See ya
