### ISSUE TITLE
Tableview says "E/RecyclerView: No adapter attached; skipping layout"

### ISSUE THREAD

**Issue by bogdanmunteanu** [evrencoskun/TableView#95]
Hi @evrencoskun ,

I followed your tutorial and compared with the sample app and cannot figure what I'm doing wrong. On the layout the table is not shown with the error
E/RecyclerView: No adapter attached; skipping layout
E/RecyclerView: No adapter attached; skipping layout
E/RecyclerView: No adapter attached; skipping layout

I am wondering what can cause this ? Below is my initialization code :

 ```java
        table = new TableView(this.getContext());
        adapter = new ExploreTableViewAdapter(this.getContext());
        table.setAdapter(adapter);
        mColumnHeaderList.add(new ColumnHeader("header","test"));
        mColumnHeaderList.add(new ColumnHeader("header2","test"));
        mRowHeaderList.add(new RowHeader("rowHeader","rowHeader"));
        mRowHeaderList.add(new RowHeader("rowHeader2","rowHeader2"));
        ArrayList<Cell> cells = new ArrayList<>();
        cells.add(new Cell("1"));
        cells.add(new Cell("2"));
        cells.add(new Cell("3"));
        mCellList.add(0,cells);
        mCellList.add(1,cells);
        mCellList.add(2,cells);
        Log.e("column headers :::",mColumnHeaderList.toString());
        Log.e("row headers :::",mRowHeaderList.toString());
        Log.e("cell :::",mCellList.toString());
        adapter.setAllItems(mColumnHeaderList,mRowHeaderList,mCellList);
        FrameLayout.LayoutParams tlp = new FrameLayout.LayoutParams(FrameLayout.LayoutParams
                .MATCH_PARENT, FrameLayout.LayoutParams.MATCH_PARENT);
        table.setLayoutParams(tlp);
```

**Comment by evrencoskun** [comment]
Hi @bogdanmunteanu,

According to the [this](https://stackoverflow.com/questions/29141729/recyclerview-no-adapter-attached-skipping-layout), there may a lot of reason to get this error.

```java
       // Create Column Header list
        ArrayList<ColumnHeader> mColumnHeaderList = new ArrayList<>();
        mColumnHeaderList.add(new ColumnHeader("header", "test"));
        mColumnHeaderList.add(new ColumnHeader("header2", "test"));

        // Create Row Header list
        ArrayList<RowHeader> mRowHeaderList = new ArrayList<>();
        mRowHeaderList.add(new RowHeader("rowHeader", "rowHeader"));
        mRowHeaderList.add(new RowHeader("rowHeader2", "rowHeader2"));

        // First row
        ArrayList<Cell> cells1 = new ArrayList<>();
        cells1.add(new Cell("1 - 1 ", " Cell 1 - 1"));
        cells1.add(new Cell("1 - 2", " Cell 1 - 2"));

        // Second row
        ArrayList<Cell> cells2 = new ArrayList<>();
        cells2.add(new Cell("2 - 1 ", " Cell 2 - 1"));
        cells2.add(new Cell("2 - 2", " Cell 2 - 2"));

        // Create Cell list
        ArrayList<ArrayList<Cell>> mCellList = new ArrayList<>();
        mCellList.add(cells1);
        mCellList.add(cells2);

        mTableViewAdapter.setAllItems(mColumnHeaderList, mRowHeaderList, mCellList);
```

Please try the above code and let me know the result.

**Comment by bogdanmunteanu** [comment]
Hi @evrencoskun ,

Still not working , but found something rather interesting . When I looked on the view hierarchy , I noticed that the Tableview is there with 3 CellRecyclerViews !? . I think they are causing the issue because if they don't have adapters attached they won't be displayed. 

From the view hierarchy
![screen shot 2018-04-28 at 09 11 42](https://user-images.githubusercontent.com/8288565/39392755-36e379d2-4ac4-11e8-89a3-25eecfcb02c8.png)

Wondering what kind of adapter is needed there and how to attach it .

**Comment by bogdanmunteanu** [comment]
The problem seems to be in TableView.java class from the library , although I'm not sure of that . 
Those adapters are set correctly on line 290 :  
  public void setAdapter(AbstractTableAdapter tableAdapter) {
        if (tableAdapter != null) {
            this.mTableAdapter = tableAdapter;
            this.mTableAdapter.setRowHeaderWidth(mRowHeaderWidth);
            this.mTableAdapter.setColumnHeaderHeight(mColumnHeaderHeight);
            this.mTableAdapter.setTableView(this);

            // set adapters
            if (mColumnHeaderRecyclerView != null) {
                mColumnHeaderRecyclerView.setAdapter(mTableAdapter
                        .getColumnHeaderRecyclerViewAdapter());
            }
            if (mRowHeaderRecyclerView != null) {
                mRowHeaderRecyclerView.setAdapter(mTableAdapter.getRowHeaderRecyclerViewAdapter());
            }
            if (mCellRecyclerView != null) {
                mCellRecyclerView.setAdapter(mTableAdapter.getCellRecyclerViewAdapter());

                // Create Sort Handler
                mColumnSortHandler = new ColumnSortHandler(this);

                // Create Filter Handler
                mFilterHandler = new FilterHandler(this);
            }
        }
    }

**Comment by evrencoskun** [comment]
Hi @bogdanmunteanu 

> Tableview is there with 3 CellRecyclerViews !?
It's pretty normal. Because TableView consists of 3 RecyclerView.

![structurecrop](https://user-images.githubusercontent.com/4228262/39392942-9b64b256-4ac7-11e8-96c3-1b6bc6623fa7.png)

Probably, you are doing something wrong in your TableViewAdapter. Because I've already tested the code that I recommend you to use.

Please share your ExploreTableViewAdapter class.

**Comment by bogdanmunteanu** [comment]
Hi @evrencoskun , 

Sure , here it is : 

  public void setAdapter(AbstractTableAdapter tableAdapter) {
        if (tableAdapter != null) {
            this.mTableAdapter = tableAdapter;
            this.mTableAdapter.setRowHeaderWidth(mRowHeaderWidth);
            this.mTableAdapter.setColumnHeaderHeight(mColumnHeaderHeight);
            this.mTableAdapter.setTableView(this);

            // set adapters
            if (mColumnHeaderRecyclerView != null) {
                mColumnHeaderRecyclerView.setAdapter(mTableAdapter
                        .getColumnHeaderRecyclerViewAdapter());
            }
            if (mRowHeaderRecyclerView != null) {
                mRowHeaderRecyclerView.setAdapter(mTableAdapter.getRowHeaderRecyclerViewAdapter());
            }
            if (mCellRecyclerView != null) {
                mCellRecyclerView.setAdapter(mTableAdapter.getCellRecyclerViewAdapter());

                // Create Sort Handler
                mColumnSortHandler = new ColumnSortHandler(this);

                // Create Filter Handler
                mFilterHandler = new FilterHandler(this);
            }
        }
    }

**Comment by bogdanmunteanu** [comment]
@evrencoskun  , sure , here it is . I'm sure I'm doing something wrong , your image helped cleared things a bit . Adapter is below :

public class ExploreTableViewAdapter extends AbstractTableAdapter<ColumnHeader,RowHeader,Cell> {

    public Context context;

    public ExploreTableViewAdapter(Context context) {
        super(context);
        this.context=context;
    }

    @Override
    public int getColumnHeaderItemViewType(int position) {
        return 0;
    }

    @Override
    public int getRowHeaderItemViewType(int position) {
        return 0;
    }

    @Override
    public int getCellItemViewType(int position) {
        return 0;
    }

    @Override
    public RecyclerView.ViewHolder onCreateCellViewHolder(ViewGroup parent, int viewType) {
        View layout = LayoutInflater.from(context).inflate(R.layout.row_cell,parent,false);
        return new MyCellViewHolder(layout);
    }

    @Override
    public void onBindCellViewHolder(AbstractViewHolder holder, Object cellItemModel, int columnPosition, int rowPosition) {
        Cell cell = (Cell) cellItemModel;

        // Get the holder to update cell item text
        MyCellViewHolder viewHolder = (MyCellViewHolder) holder;
        viewHolder.text.setText("Test");

        // If your TableView should have auto resize for cells & columns.
        // Then you should consider the below lines. Otherwise, you can ignore them.

        // It is necessary to remeasure itself.
        viewHolder.itemView.getLayoutParams().width = LinearLayout.LayoutParams.WRAP_CONTENT;
        viewHolder.text.requestLayout();
    }

    @Override
    public RecyclerView.ViewHolder onCreateColumnHeaderViewHolder(ViewGroup parent, int viewType) {
        View layout = LayoutInflater.from(context).inflate(R.layout.row_cell,parent,false);
        return new MyCellHeaderViewHolder(layout);
    }

    @Override
    public void onBindColumnHeaderViewHolder(AbstractViewHolder holder, Object columnHeaderItemModel, int columnPosition) {
        MyCellHeaderViewHolder viewHolder = (MyCellHeaderViewHolder) holder;
        viewHolder.text.setText("Test");
    }



    //row header
    @Override
    public RecyclerView.ViewHolder onCreateRowHeaderViewHolder(ViewGroup parent, int viewType) {
        View layout = LayoutInflater.from(context).inflate(R.layout.row_header, parent, false);

        // Create a Row Header ViewHolder
        return new MyRowHeaderViewHolder(layout);
    }

    @Override
    public void onBindRowHeaderViewHolder(AbstractViewHolder holder, Object rowHeaderItemModel, int rowPosition) {
        RowHeader rowHeader = (RowHeader) rowHeaderItemModel;

        // Get the holder to update row header item text
        MyRowHeaderViewHolder rowHeaderViewHolder = (MyRowHeaderViewHolder) holder;
    }

    @Override
    public View onCreateCornerView() {
        return LayoutInflater.from(context).inflate(R.layout.row_cell, null);
    }


    class MyRowHeaderViewHolder extends AbstractViewHolder {
        //butterknife here

        public MyRowHeaderViewHolder(View itemView) {
            super(itemView);

        }
    }

    class MyCellViewHolder extends AbstractViewHolder
    {

        @BindView(R.id.text)
        TextView text;

        public MyCellViewHolder(View itemView) {
            super(itemView);
            ButterKnife.bind(itemView);
        }
    }

    class MyCellHeaderViewHolder extends AbstractViewHolder
    {

        @BindView(R.id.text)
        TextView text;

        public MyCellHeaderViewHolder(View itemView) {
            super(itemView);
            ButterKnife.bind(itemView);

        }
    }
}

**Comment by bogdanmunteanu** [comment]
@evrencoskun  hav you figured out what's wrong with my code ? I really need to use this library :D

**Comment by evrencoskun** [comment]
Actually, there are a lot of things that seem strange.

For example, you don't set any text to your row header ViewHolder. 

Just, copy and paste the working [adapter](https://github.com/evrencoskun/TableView#2-create-your-tableviewadapter) in the sample. And change it according to your own needs.

**Comment by bogdanmunteanu** [comment]
@evrencoskun  you can close this as well. For anyone that is having trouble implementing this , just use the adapter from the sample and start from there :)
